package org.ys.crawler.model;

import java.io.Serializable;
import java.util.Date;

public class FootballScore implements Serializable {
    private static final long serialVersionUID = -6303078343468218195L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.football_score_id
     *
     * @mbg.generated
     */
    private String footballScoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.home_football_team_id
     *
     * @mbg.generated
     */
    private String homeFootballTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.away_football_team_id
     *
     * @mbg.generated
     */
    private String awayFootballTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.home_score
     *
     * @mbg.generated
     */
    private Integer homeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.away_score
     *
     * @mbg.generated
     */
    private Integer awayScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.half_home_score
     *
     * @mbg.generated
     */
    private Integer halfHomeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.half_away_score
     *
     * @mbg.generated
     */
    private Integer halfAwayScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.match_date
     *
     * @mbg.generated
     */
    private Date matchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.football_league_match_id
     *
     * @mbg.generated
     */
    private String footballLeagueMatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.football_season_category_id
     *
     * @mbg.generated
     */
    private String footballSeasonCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.football_season_id
     *
     * @mbg.generated
     */
    private String footballSeasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.round
     *
     * @mbg.generated
     */
    private String round;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_score.leidata_score_id
     *
     * @mbg.generated
     */
    private String leidataScoreId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.football_score_id
     *
     * @return the value of cr_football_score.football_score_id
     *
     * @mbg.generated
     */
    public String getFootballScoreId() {
        return footballScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.football_score_id
     *
     * @param footballScoreId the value for cr_football_score.football_score_id
     *
     * @mbg.generated
     */
    public void setFootballScoreId(String footballScoreId) {
        this.footballScoreId = footballScoreId == null ? null : footballScoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.home_football_team_id
     *
     * @return the value of cr_football_score.home_football_team_id
     *
     * @mbg.generated
     */
    public String getHomeFootballTeamId() {
        return homeFootballTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.home_football_team_id
     *
     * @param homeFootballTeamId the value for cr_football_score.home_football_team_id
     *
     * @mbg.generated
     */
    public void setHomeFootballTeamId(String homeFootballTeamId) {
        this.homeFootballTeamId = homeFootballTeamId == null ? null : homeFootballTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.away_football_team_id
     *
     * @return the value of cr_football_score.away_football_team_id
     *
     * @mbg.generated
     */
    public String getAwayFootballTeamId() {
        return awayFootballTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.away_football_team_id
     *
     * @param awayFootballTeamId the value for cr_football_score.away_football_team_id
     *
     * @mbg.generated
     */
    public void setAwayFootballTeamId(String awayFootballTeamId) {
        this.awayFootballTeamId = awayFootballTeamId == null ? null : awayFootballTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.home_score
     *
     * @return the value of cr_football_score.home_score
     *
     * @mbg.generated
     */
    public Integer getHomeScore() {
        return homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.home_score
     *
     * @param homeScore the value for cr_football_score.home_score
     *
     * @mbg.generated
     */
    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.away_score
     *
     * @return the value of cr_football_score.away_score
     *
     * @mbg.generated
     */
    public Integer getAwayScore() {
        return awayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.away_score
     *
     * @param awayScore the value for cr_football_score.away_score
     *
     * @mbg.generated
     */
    public void setAwayScore(Integer awayScore) {
        this.awayScore = awayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.half_home_score
     *
     * @return the value of cr_football_score.half_home_score
     *
     * @mbg.generated
     */
    public Integer getHalfHomeScore() {
        return halfHomeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.half_home_score
     *
     * @param halfHomeScore the value for cr_football_score.half_home_score
     *
     * @mbg.generated
     */
    public void setHalfHomeScore(Integer halfHomeScore) {
        this.halfHomeScore = halfHomeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.half_away_score
     *
     * @return the value of cr_football_score.half_away_score
     *
     * @mbg.generated
     */
    public Integer getHalfAwayScore() {
        return halfAwayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.half_away_score
     *
     * @param halfAwayScore the value for cr_football_score.half_away_score
     *
     * @mbg.generated
     */
    public void setHalfAwayScore(Integer halfAwayScore) {
        this.halfAwayScore = halfAwayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.match_date
     *
     * @return the value of cr_football_score.match_date
     *
     * @mbg.generated
     */
    public Date getMatchDate() {
        return matchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.match_date
     *
     * @param matchDate the value for cr_football_score.match_date
     *
     * @mbg.generated
     */
    public void setMatchDate(Date matchDate) {
        this.matchDate = matchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.football_league_match_id
     *
     * @return the value of cr_football_score.football_league_match_id
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchId() {
        return footballLeagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.football_league_match_id
     *
     * @param footballLeagueMatchId the value for cr_football_score.football_league_match_id
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchId(String footballLeagueMatchId) {
        this.footballLeagueMatchId = footballLeagueMatchId == null ? null : footballLeagueMatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.football_season_category_id
     *
     * @return the value of cr_football_score.football_season_category_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonCategoryId() {
        return footballSeasonCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.football_season_category_id
     *
     * @param footballSeasonCategoryId the value for cr_football_score.football_season_category_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonCategoryId(String footballSeasonCategoryId) {
        this.footballSeasonCategoryId = footballSeasonCategoryId == null ? null : footballSeasonCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.football_season_id
     *
     * @return the value of cr_football_score.football_season_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonId() {
        return footballSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.football_season_id
     *
     * @param footballSeasonId the value for cr_football_score.football_season_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonId(String footballSeasonId) {
        this.footballSeasonId = footballSeasonId == null ? null : footballSeasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.round
     *
     * @return the value of cr_football_score.round
     *
     * @mbg.generated
     */
    public String getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.round
     *
     * @param round the value for cr_football_score.round
     *
     * @mbg.generated
     */
    public void setRound(String round) {
        this.round = round == null ? null : round.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_score.leidata_score_id
     *
     * @return the value of cr_football_score.leidata_score_id
     *
     * @mbg.generated
     */
    public String getLeidataScoreId() {
        return leidataScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_score.leidata_score_id
     *
     * @param leidataScoreId the value for cr_football_score.leidata_score_id
     *
     * @mbg.generated
     */
    public void setLeidataScoreId(String leidataScoreId) {
        this.leidataScoreId = leidataScoreId == null ? null : leidataScoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballScore other = (FootballScore) that;
        return (this.getFootballScoreId() == null ? other.getFootballScoreId() == null : this.getFootballScoreId().equals(other.getFootballScoreId()))
            && (this.getHomeFootballTeamId() == null ? other.getHomeFootballTeamId() == null : this.getHomeFootballTeamId().equals(other.getHomeFootballTeamId()))
            && (this.getAwayFootballTeamId() == null ? other.getAwayFootballTeamId() == null : this.getAwayFootballTeamId().equals(other.getAwayFootballTeamId()))
            && (this.getHomeScore() == null ? other.getHomeScore() == null : this.getHomeScore().equals(other.getHomeScore()))
            && (this.getAwayScore() == null ? other.getAwayScore() == null : this.getAwayScore().equals(other.getAwayScore()))
            && (this.getHalfHomeScore() == null ? other.getHalfHomeScore() == null : this.getHalfHomeScore().equals(other.getHalfHomeScore()))
            && (this.getHalfAwayScore() == null ? other.getHalfAwayScore() == null : this.getHalfAwayScore().equals(other.getHalfAwayScore()))
            && (this.getMatchDate() == null ? other.getMatchDate() == null : this.getMatchDate().equals(other.getMatchDate()))
            && (this.getFootballLeagueMatchId() == null ? other.getFootballLeagueMatchId() == null : this.getFootballLeagueMatchId().equals(other.getFootballLeagueMatchId()))
            && (this.getFootballSeasonCategoryId() == null ? other.getFootballSeasonCategoryId() == null : this.getFootballSeasonCategoryId().equals(other.getFootballSeasonCategoryId()))
            && (this.getFootballSeasonId() == null ? other.getFootballSeasonId() == null : this.getFootballSeasonId().equals(other.getFootballSeasonId()))
            && (this.getRound() == null ? other.getRound() == null : this.getRound().equals(other.getRound()))
            && (this.getLeidataScoreId() == null ? other.getLeidataScoreId() == null : this.getLeidataScoreId().equals(other.getLeidataScoreId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballScoreId() == null) ? 0 : getFootballScoreId().hashCode());
        result = prime * result + ((getHomeFootballTeamId() == null) ? 0 : getHomeFootballTeamId().hashCode());
        result = prime * result + ((getAwayFootballTeamId() == null) ? 0 : getAwayFootballTeamId().hashCode());
        result = prime * result + ((getHomeScore() == null) ? 0 : getHomeScore().hashCode());
        result = prime * result + ((getAwayScore() == null) ? 0 : getAwayScore().hashCode());
        result = prime * result + ((getHalfHomeScore() == null) ? 0 : getHalfHomeScore().hashCode());
        result = prime * result + ((getHalfAwayScore() == null) ? 0 : getHalfAwayScore().hashCode());
        result = prime * result + ((getMatchDate() == null) ? 0 : getMatchDate().hashCode());
        result = prime * result + ((getFootballLeagueMatchId() == null) ? 0 : getFootballLeagueMatchId().hashCode());
        result = prime * result + ((getFootballSeasonCategoryId() == null) ? 0 : getFootballSeasonCategoryId().hashCode());
        result = prime * result + ((getFootballSeasonId() == null) ? 0 : getFootballSeasonId().hashCode());
        result = prime * result + ((getRound() == null) ? 0 : getRound().hashCode());
        result = prime * result + ((getLeidataScoreId() == null) ? 0 : getLeidataScoreId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballScoreId=").append(footballScoreId);
        sb.append(", homeFootballTeamId=").append(homeFootballTeamId);
        sb.append(", awayFootballTeamId=").append(awayFootballTeamId);
        sb.append(", homeScore=").append(homeScore);
        sb.append(", awayScore=").append(awayScore);
        sb.append(", halfHomeScore=").append(halfHomeScore);
        sb.append(", halfAwayScore=").append(halfAwayScore);
        sb.append(", matchDate=").append(matchDate);
        sb.append(", footballLeagueMatchId=").append(footballLeagueMatchId);
        sb.append(", footballSeasonCategoryId=").append(footballSeasonCategoryId);
        sb.append(", footballSeasonId=").append(footballSeasonId);
        sb.append(", round=").append(round);
        sb.append(", leidataScoreId=").append(leidataScoreId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}