package org.ys.crawler.model;

import java.util.ArrayList;
import java.util.List;

public class FootballIntegralExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public FootballIntegralExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFootballIntegralIdIsNull() {
            addCriterion("football_integral_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdIsNotNull() {
            addCriterion("football_integral_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdEqualTo(String value) {
            addCriterion("football_integral_id =", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdNotEqualTo(String value) {
            addCriterion("football_integral_id <>", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdGreaterThan(String value) {
            addCriterion("football_integral_id >", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_integral_id >=", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdLessThan(String value) {
            addCriterion("football_integral_id <", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdLessThanOrEqualTo(String value) {
            addCriterion("football_integral_id <=", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdLike(String value) {
            addCriterion("football_integral_id like", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdNotLike(String value) {
            addCriterion("football_integral_id not like", value, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdIn(List<String> values) {
            addCriterion("football_integral_id in", values, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdNotIn(List<String> values) {
            addCriterion("football_integral_id not in", values, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdBetween(String value1, String value2) {
            addCriterion("football_integral_id between", value1, value2, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballIntegralIdNotBetween(String value1, String value2) {
            addCriterion("football_integral_id not between", value1, value2, "footballIntegralId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNull() {
            addCriterion("football_league_match_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNotNull() {
            addCriterion("football_league_match_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdEqualTo(String value) {
            addCriterion("football_league_match_id =", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotEqualTo(String value) {
            addCriterion("football_league_match_id <>", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThan(String value) {
            addCriterion("football_league_match_id >", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_id >=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThan(String value) {
            addCriterion("football_league_match_id <", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_id <=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLike(String value) {
            addCriterion("football_league_match_id like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotLike(String value) {
            addCriterion("football_league_match_id not like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIn(List<String> values) {
            addCriterion("football_league_match_id in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotIn(List<String> values) {
            addCriterion("football_league_match_id not in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdBetween(String value1, String value2) {
            addCriterion("football_league_match_id between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotBetween(String value1, String value2) {
            addCriterion("football_league_match_id not between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNull() {
            addCriterion("football_season_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNotNull() {
            addCriterion("football_season_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdEqualTo(String value) {
            addCriterion("football_season_id =", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotEqualTo(String value) {
            addCriterion("football_season_id <>", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThan(String value) {
            addCriterion("football_season_id >", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_id >=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThan(String value) {
            addCriterion("football_season_id <", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_id <=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLike(String value) {
            addCriterion("football_season_id like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotLike(String value) {
            addCriterion("football_season_id not like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIn(List<String> values) {
            addCriterion("football_season_id in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotIn(List<String> values) {
            addCriterion("football_season_id not in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdBetween(String value1, String value2) {
            addCriterion("football_season_id between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotBetween(String value1, String value2) {
            addCriterion("football_season_id not between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIsNull() {
            addCriterion("football_season_category_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIsNotNull() {
            addCriterion("football_season_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdEqualTo(String value) {
            addCriterion("football_season_category_id =", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotEqualTo(String value) {
            addCriterion("football_season_category_id <>", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThan(String value) {
            addCriterion("football_season_category_id >", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_category_id >=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThan(String value) {
            addCriterion("football_season_category_id <", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_category_id <=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLike(String value) {
            addCriterion("football_season_category_id like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotLike(String value) {
            addCriterion("football_season_category_id not like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIn(List<String> values) {
            addCriterion("football_season_category_id in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotIn(List<String> values) {
            addCriterion("football_season_category_id not in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdBetween(String value1, String value2) {
            addCriterion("football_season_category_id between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotBetween(String value1, String value2) {
            addCriterion("football_season_category_id not between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIsNull() {
            addCriterion("football_team_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIsNotNull() {
            addCriterion("football_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdEqualTo(String value) {
            addCriterion("football_team_id =", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotEqualTo(String value) {
            addCriterion("football_team_id <>", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdGreaterThan(String value) {
            addCriterion("football_team_id >", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_team_id >=", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLessThan(String value) {
            addCriterion("football_team_id <", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLessThanOrEqualTo(String value) {
            addCriterion("football_team_id <=", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLike(String value) {
            addCriterion("football_team_id like", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotLike(String value) {
            addCriterion("football_team_id not like", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIn(List<String> values) {
            addCriterion("football_team_id in", values, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotIn(List<String> values) {
            addCriterion("football_team_id not in", values, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdBetween(String value1, String value2) {
            addCriterion("football_team_id between", value1, value2, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotBetween(String value1, String value2) {
            addCriterion("football_team_id not between", value1, value2, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalIsNull() {
            addCriterion("integral_total is null");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalIsNotNull() {
            addCriterion("integral_total is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalEqualTo(Integer value) {
            addCriterion("integral_total =", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalNotEqualTo(Integer value) {
            addCriterion("integral_total <>", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalGreaterThan(Integer value) {
            addCriterion("integral_total >", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("integral_total >=", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalLessThan(Integer value) {
            addCriterion("integral_total <", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalLessThanOrEqualTo(Integer value) {
            addCriterion("integral_total <=", value, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalIn(List<Integer> values) {
            addCriterion("integral_total in", values, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalNotIn(List<Integer> values) {
            addCriterion("integral_total not in", values, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalBetween(Integer value1, Integer value2) {
            addCriterion("integral_total between", value1, value2, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andIntegralTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("integral_total not between", value1, value2, "integralTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalIsNull() {
            addCriterion("goal_total is null");
            return (Criteria) this;
        }

        public Criteria andGoalTotalIsNotNull() {
            addCriterion("goal_total is not null");
            return (Criteria) this;
        }

        public Criteria andGoalTotalEqualTo(Integer value) {
            addCriterion("goal_total =", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalNotEqualTo(Integer value) {
            addCriterion("goal_total <>", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalGreaterThan(Integer value) {
            addCriterion("goal_total >", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("goal_total >=", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalLessThan(Integer value) {
            addCriterion("goal_total <", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalLessThanOrEqualTo(Integer value) {
            addCriterion("goal_total <=", value, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalIn(List<Integer> values) {
            addCriterion("goal_total in", values, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalNotIn(List<Integer> values) {
            addCriterion("goal_total not in", values, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalBetween(Integer value1, Integer value2) {
            addCriterion("goal_total between", value1, value2, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andGoalTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("goal_total not between", value1, value2, "goalTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalIsNull() {
            addCriterion("fumble_total is null");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalIsNotNull() {
            addCriterion("fumble_total is not null");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalEqualTo(Integer value) {
            addCriterion("fumble_total =", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalNotEqualTo(Integer value) {
            addCriterion("fumble_total <>", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalGreaterThan(Integer value) {
            addCriterion("fumble_total >", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("fumble_total >=", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalLessThan(Integer value) {
            addCriterion("fumble_total <", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalLessThanOrEqualTo(Integer value) {
            addCriterion("fumble_total <=", value, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalIn(List<Integer> values) {
            addCriterion("fumble_total in", values, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalNotIn(List<Integer> values) {
            addCriterion("fumble_total not in", values, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalBetween(Integer value1, Integer value2) {
            addCriterion("fumble_total between", value1, value2, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andFumbleTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("fumble_total not between", value1, value2, "fumbleTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalIsNull() {
            addCriterion("difference_total is null");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalIsNotNull() {
            addCriterion("difference_total is not null");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalEqualTo(Integer value) {
            addCriterion("difference_total =", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalNotEqualTo(Integer value) {
            addCriterion("difference_total <>", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalGreaterThan(Integer value) {
            addCriterion("difference_total >", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("difference_total >=", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalLessThan(Integer value) {
            addCriterion("difference_total <", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalLessThanOrEqualTo(Integer value) {
            addCriterion("difference_total <=", value, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalIn(List<Integer> values) {
            addCriterion("difference_total in", values, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalNotIn(List<Integer> values) {
            addCriterion("difference_total not in", values, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalBetween(Integer value1, Integer value2) {
            addCriterion("difference_total between", value1, value2, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andDifferenceTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("difference_total not between", value1, value2, "differenceTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalIsNull() {
            addCriterion("played_total is null");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalIsNotNull() {
            addCriterion("played_total is not null");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalEqualTo(Integer value) {
            addCriterion("played_total =", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalNotEqualTo(Integer value) {
            addCriterion("played_total <>", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalGreaterThan(Integer value) {
            addCriterion("played_total >", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("played_total >=", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalLessThan(Integer value) {
            addCriterion("played_total <", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalLessThanOrEqualTo(Integer value) {
            addCriterion("played_total <=", value, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalIn(List<Integer> values) {
            addCriterion("played_total in", values, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalNotIn(List<Integer> values) {
            addCriterion("played_total not in", values, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalBetween(Integer value1, Integer value2) {
            addCriterion("played_total between", value1, value2, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andPlayedTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("played_total not between", value1, value2, "playedTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalIsNull() {
            addCriterion("win_total is null");
            return (Criteria) this;
        }

        public Criteria andWinTotalIsNotNull() {
            addCriterion("win_total is not null");
            return (Criteria) this;
        }

        public Criteria andWinTotalEqualTo(Integer value) {
            addCriterion("win_total =", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalNotEqualTo(Integer value) {
            addCriterion("win_total <>", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalGreaterThan(Integer value) {
            addCriterion("win_total >", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_total >=", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalLessThan(Integer value) {
            addCriterion("win_total <", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalLessThanOrEqualTo(Integer value) {
            addCriterion("win_total <=", value, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalIn(List<Integer> values) {
            addCriterion("win_total in", values, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalNotIn(List<Integer> values) {
            addCriterion("win_total not in", values, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalBetween(Integer value1, Integer value2) {
            addCriterion("win_total between", value1, value2, "winTotal");
            return (Criteria) this;
        }

        public Criteria andWinTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("win_total not between", value1, value2, "winTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalIsNull() {
            addCriterion("draw_total is null");
            return (Criteria) this;
        }

        public Criteria andDrawTotalIsNotNull() {
            addCriterion("draw_total is not null");
            return (Criteria) this;
        }

        public Criteria andDrawTotalEqualTo(Integer value) {
            addCriterion("draw_total =", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalNotEqualTo(Integer value) {
            addCriterion("draw_total <>", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalGreaterThan(Integer value) {
            addCriterion("draw_total >", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_total >=", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalLessThan(Integer value) {
            addCriterion("draw_total <", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalLessThanOrEqualTo(Integer value) {
            addCriterion("draw_total <=", value, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalIn(List<Integer> values) {
            addCriterion("draw_total in", values, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalNotIn(List<Integer> values) {
            addCriterion("draw_total not in", values, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalBetween(Integer value1, Integer value2) {
            addCriterion("draw_total between", value1, value2, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andDrawTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_total not between", value1, value2, "drawTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalIsNull() {
            addCriterion("lost_total is null");
            return (Criteria) this;
        }

        public Criteria andLostTotalIsNotNull() {
            addCriterion("lost_total is not null");
            return (Criteria) this;
        }

        public Criteria andLostTotalEqualTo(Integer value) {
            addCriterion("lost_total =", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalNotEqualTo(Integer value) {
            addCriterion("lost_total <>", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalGreaterThan(Integer value) {
            addCriterion("lost_total >", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("lost_total >=", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalLessThan(Integer value) {
            addCriterion("lost_total <", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalLessThanOrEqualTo(Integer value) {
            addCriterion("lost_total <=", value, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalIn(List<Integer> values) {
            addCriterion("lost_total in", values, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalNotIn(List<Integer> values) {
            addCriterion("lost_total not in", values, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalBetween(Integer value1, Integer value2) {
            addCriterion("lost_total between", value1, value2, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andLostTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("lost_total not between", value1, value2, "lostTotal");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedIsNull() {
            addCriterion("goal_per_played is null");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedIsNotNull() {
            addCriterion("goal_per_played is not null");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedEqualTo(Float value) {
            addCriterion("goal_per_played =", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedNotEqualTo(Float value) {
            addCriterion("goal_per_played <>", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedGreaterThan(Float value) {
            addCriterion("goal_per_played >", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedGreaterThanOrEqualTo(Float value) {
            addCriterion("goal_per_played >=", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedLessThan(Float value) {
            addCriterion("goal_per_played <", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedLessThanOrEqualTo(Float value) {
            addCriterion("goal_per_played <=", value, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedIn(List<Float> values) {
            addCriterion("goal_per_played in", values, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedNotIn(List<Float> values) {
            addCriterion("goal_per_played not in", values, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedBetween(Float value1, Float value2) {
            addCriterion("goal_per_played between", value1, value2, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andGoalPerPlayedNotBetween(Float value1, Float value2) {
            addCriterion("goal_per_played not between", value1, value2, "goalPerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedIsNull() {
            addCriterion("fumble_per_played is null");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedIsNotNull() {
            addCriterion("fumble_per_played is not null");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedEqualTo(Float value) {
            addCriterion("fumble_per_played =", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedNotEqualTo(Float value) {
            addCriterion("fumble_per_played <>", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedGreaterThan(Float value) {
            addCriterion("fumble_per_played >", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedGreaterThanOrEqualTo(Float value) {
            addCriterion("fumble_per_played >=", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedLessThan(Float value) {
            addCriterion("fumble_per_played <", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedLessThanOrEqualTo(Float value) {
            addCriterion("fumble_per_played <=", value, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedIn(List<Float> values) {
            addCriterion("fumble_per_played in", values, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedNotIn(List<Float> values) {
            addCriterion("fumble_per_played not in", values, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedBetween(Float value1, Float value2) {
            addCriterion("fumble_per_played between", value1, value2, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andFumblePerPlayedNotBetween(Float value1, Float value2) {
            addCriterion("fumble_per_played not between", value1, value2, "fumblePerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedIsNull() {
            addCriterion("win_per_played is null");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedIsNotNull() {
            addCriterion("win_per_played is not null");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedEqualTo(Float value) {
            addCriterion("win_per_played =", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedNotEqualTo(Float value) {
            addCriterion("win_per_played <>", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedGreaterThan(Float value) {
            addCriterion("win_per_played >", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedGreaterThanOrEqualTo(Float value) {
            addCriterion("win_per_played >=", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedLessThan(Float value) {
            addCriterion("win_per_played <", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedLessThanOrEqualTo(Float value) {
            addCriterion("win_per_played <=", value, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedIn(List<Float> values) {
            addCriterion("win_per_played in", values, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedNotIn(List<Float> values) {
            addCriterion("win_per_played not in", values, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedBetween(Float value1, Float value2) {
            addCriterion("win_per_played between", value1, value2, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinPerPlayedNotBetween(Float value1, Float value2) {
            addCriterion("win_per_played not between", value1, value2, "winPerPlayed");
            return (Criteria) this;
        }

        public Criteria andWinHomeIsNull() {
            addCriterion("win_home is null");
            return (Criteria) this;
        }

        public Criteria andWinHomeIsNotNull() {
            addCriterion("win_home is not null");
            return (Criteria) this;
        }

        public Criteria andWinHomeEqualTo(Integer value) {
            addCriterion("win_home =", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeNotEqualTo(Integer value) {
            addCriterion("win_home <>", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeGreaterThan(Integer value) {
            addCriterion("win_home >", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_home >=", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeLessThan(Integer value) {
            addCriterion("win_home <", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeLessThanOrEqualTo(Integer value) {
            addCriterion("win_home <=", value, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeIn(List<Integer> values) {
            addCriterion("win_home in", values, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeNotIn(List<Integer> values) {
            addCriterion("win_home not in", values, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeBetween(Integer value1, Integer value2) {
            addCriterion("win_home between", value1, value2, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("win_home not between", value1, value2, "winHome");
            return (Criteria) this;
        }

        public Criteria andWinAwayIsNull() {
            addCriterion("win_away is null");
            return (Criteria) this;
        }

        public Criteria andWinAwayIsNotNull() {
            addCriterion("win_away is not null");
            return (Criteria) this;
        }

        public Criteria andWinAwayEqualTo(Integer value) {
            addCriterion("win_away =", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayNotEqualTo(Integer value) {
            addCriterion("win_away <>", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayGreaterThan(Integer value) {
            addCriterion("win_away >", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_away >=", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayLessThan(Integer value) {
            addCriterion("win_away <", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayLessThanOrEqualTo(Integer value) {
            addCriterion("win_away <=", value, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayIn(List<Integer> values) {
            addCriterion("win_away in", values, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayNotIn(List<Integer> values) {
            addCriterion("win_away not in", values, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayBetween(Integer value1, Integer value2) {
            addCriterion("win_away between", value1, value2, "winAway");
            return (Criteria) this;
        }

        public Criteria andWinAwayNotBetween(Integer value1, Integer value2) {
            addCriterion("win_away not between", value1, value2, "winAway");
            return (Criteria) this;
        }

        public Criteria andDrawHomeIsNull() {
            addCriterion("draw_home is null");
            return (Criteria) this;
        }

        public Criteria andDrawHomeIsNotNull() {
            addCriterion("draw_home is not null");
            return (Criteria) this;
        }

        public Criteria andDrawHomeEqualTo(Integer value) {
            addCriterion("draw_home =", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeNotEqualTo(Integer value) {
            addCriterion("draw_home <>", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeGreaterThan(Integer value) {
            addCriterion("draw_home >", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_home >=", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeLessThan(Integer value) {
            addCriterion("draw_home <", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeLessThanOrEqualTo(Integer value) {
            addCriterion("draw_home <=", value, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeIn(List<Integer> values) {
            addCriterion("draw_home in", values, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeNotIn(List<Integer> values) {
            addCriterion("draw_home not in", values, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeBetween(Integer value1, Integer value2) {
            addCriterion("draw_home between", value1, value2, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_home not between", value1, value2, "drawHome");
            return (Criteria) this;
        }

        public Criteria andDrawAwayIsNull() {
            addCriterion("draw_away is null");
            return (Criteria) this;
        }

        public Criteria andDrawAwayIsNotNull() {
            addCriterion("draw_away is not null");
            return (Criteria) this;
        }

        public Criteria andDrawAwayEqualTo(Integer value) {
            addCriterion("draw_away =", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayNotEqualTo(Integer value) {
            addCriterion("draw_away <>", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayGreaterThan(Integer value) {
            addCriterion("draw_away >", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_away >=", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayLessThan(Integer value) {
            addCriterion("draw_away <", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayLessThanOrEqualTo(Integer value) {
            addCriterion("draw_away <=", value, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayIn(List<Integer> values) {
            addCriterion("draw_away in", values, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayNotIn(List<Integer> values) {
            addCriterion("draw_away not in", values, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayBetween(Integer value1, Integer value2) {
            addCriterion("draw_away between", value1, value2, "drawAway");
            return (Criteria) this;
        }

        public Criteria andDrawAwayNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_away not between", value1, value2, "drawAway");
            return (Criteria) this;
        }

        public Criteria andLostHomeIsNull() {
            addCriterion("lost_home is null");
            return (Criteria) this;
        }

        public Criteria andLostHomeIsNotNull() {
            addCriterion("lost_home is not null");
            return (Criteria) this;
        }

        public Criteria andLostHomeEqualTo(Integer value) {
            addCriterion("lost_home =", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeNotEqualTo(Integer value) {
            addCriterion("lost_home <>", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeGreaterThan(Integer value) {
            addCriterion("lost_home >", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("lost_home >=", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeLessThan(Integer value) {
            addCriterion("lost_home <", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeLessThanOrEqualTo(Integer value) {
            addCriterion("lost_home <=", value, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeIn(List<Integer> values) {
            addCriterion("lost_home in", values, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeNotIn(List<Integer> values) {
            addCriterion("lost_home not in", values, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeBetween(Integer value1, Integer value2) {
            addCriterion("lost_home between", value1, value2, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("lost_home not between", value1, value2, "lostHome");
            return (Criteria) this;
        }

        public Criteria andLostAwayIsNull() {
            addCriterion("lost_away is null");
            return (Criteria) this;
        }

        public Criteria andLostAwayIsNotNull() {
            addCriterion("lost_away is not null");
            return (Criteria) this;
        }

        public Criteria andLostAwayEqualTo(Integer value) {
            addCriterion("lost_away =", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayNotEqualTo(Integer value) {
            addCriterion("lost_away <>", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayGreaterThan(Integer value) {
            addCriterion("lost_away >", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("lost_away >=", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayLessThan(Integer value) {
            addCriterion("lost_away <", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayLessThanOrEqualTo(Integer value) {
            addCriterion("lost_away <=", value, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayIn(List<Integer> values) {
            addCriterion("lost_away in", values, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayNotIn(List<Integer> values) {
            addCriterion("lost_away not in", values, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayBetween(Integer value1, Integer value2) {
            addCriterion("lost_away between", value1, value2, "lostAway");
            return (Criteria) this;
        }

        public Criteria andLostAwayNotBetween(Integer value1, Integer value2) {
            addCriterion("lost_away not between", value1, value2, "lostAway");
            return (Criteria) this;
        }

        public Criteria andGoalHomeIsNull() {
            addCriterion("goal_home is null");
            return (Criteria) this;
        }

        public Criteria andGoalHomeIsNotNull() {
            addCriterion("goal_home is not null");
            return (Criteria) this;
        }

        public Criteria andGoalHomeEqualTo(Integer value) {
            addCriterion("goal_home =", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeNotEqualTo(Integer value) {
            addCriterion("goal_home <>", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeGreaterThan(Integer value) {
            addCriterion("goal_home >", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("goal_home >=", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeLessThan(Integer value) {
            addCriterion("goal_home <", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeLessThanOrEqualTo(Integer value) {
            addCriterion("goal_home <=", value, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeIn(List<Integer> values) {
            addCriterion("goal_home in", values, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeNotIn(List<Integer> values) {
            addCriterion("goal_home not in", values, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeBetween(Integer value1, Integer value2) {
            addCriterion("goal_home between", value1, value2, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("goal_home not between", value1, value2, "goalHome");
            return (Criteria) this;
        }

        public Criteria andGoalAwayIsNull() {
            addCriterion("goal_away is null");
            return (Criteria) this;
        }

        public Criteria andGoalAwayIsNotNull() {
            addCriterion("goal_away is not null");
            return (Criteria) this;
        }

        public Criteria andGoalAwayEqualTo(Integer value) {
            addCriterion("goal_away =", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayNotEqualTo(Integer value) {
            addCriterion("goal_away <>", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayGreaterThan(Integer value) {
            addCriterion("goal_away >", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("goal_away >=", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayLessThan(Integer value) {
            addCriterion("goal_away <", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayLessThanOrEqualTo(Integer value) {
            addCriterion("goal_away <=", value, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayIn(List<Integer> values) {
            addCriterion("goal_away in", values, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayNotIn(List<Integer> values) {
            addCriterion("goal_away not in", values, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayBetween(Integer value1, Integer value2) {
            addCriterion("goal_away between", value1, value2, "goalAway");
            return (Criteria) this;
        }

        public Criteria andGoalAwayNotBetween(Integer value1, Integer value2) {
            addCriterion("goal_away not between", value1, value2, "goalAway");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeIsNull() {
            addCriterion("fumble_home is null");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeIsNotNull() {
            addCriterion("fumble_home is not null");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeEqualTo(Integer value) {
            addCriterion("fumble_home =", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeNotEqualTo(Integer value) {
            addCriterion("fumble_home <>", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeGreaterThan(Integer value) {
            addCriterion("fumble_home >", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fumble_home >=", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeLessThan(Integer value) {
            addCriterion("fumble_home <", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeLessThanOrEqualTo(Integer value) {
            addCriterion("fumble_home <=", value, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeIn(List<Integer> values) {
            addCriterion("fumble_home in", values, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeNotIn(List<Integer> values) {
            addCriterion("fumble_home not in", values, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeBetween(Integer value1, Integer value2) {
            addCriterion("fumble_home between", value1, value2, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("fumble_home not between", value1, value2, "fumbleHome");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayIsNull() {
            addCriterion("fumble_away is null");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayIsNotNull() {
            addCriterion("fumble_away is not null");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayEqualTo(Integer value) {
            addCriterion("fumble_away =", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayNotEqualTo(Integer value) {
            addCriterion("fumble_away <>", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayGreaterThan(Integer value) {
            addCriterion("fumble_away >", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("fumble_away >=", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayLessThan(Integer value) {
            addCriterion("fumble_away <", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayLessThanOrEqualTo(Integer value) {
            addCriterion("fumble_away <=", value, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayIn(List<Integer> values) {
            addCriterion("fumble_away in", values, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayNotIn(List<Integer> values) {
            addCriterion("fumble_away not in", values, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayBetween(Integer value1, Integer value2) {
            addCriterion("fumble_away between", value1, value2, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andFumbleAwayNotBetween(Integer value1, Integer value2) {
            addCriterion("fumble_away not between", value1, value2, "fumbleAway");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdIsNull() {
            addCriterion("lei_data_integral_id is null");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdIsNotNull() {
            addCriterion("lei_data_integral_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdEqualTo(String value) {
            addCriterion("lei_data_integral_id =", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdNotEqualTo(String value) {
            addCriterion("lei_data_integral_id <>", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdGreaterThan(String value) {
            addCriterion("lei_data_integral_id >", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdGreaterThanOrEqualTo(String value) {
            addCriterion("lei_data_integral_id >=", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdLessThan(String value) {
            addCriterion("lei_data_integral_id <", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdLessThanOrEqualTo(String value) {
            addCriterion("lei_data_integral_id <=", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdLike(String value) {
            addCriterion("lei_data_integral_id like", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdNotLike(String value) {
            addCriterion("lei_data_integral_id not like", value, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdIn(List<String> values) {
            addCriterion("lei_data_integral_id in", values, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdNotIn(List<String> values) {
            addCriterion("lei_data_integral_id not in", values, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdBetween(String value1, String value2) {
            addCriterion("lei_data_integral_id between", value1, value2, "leiDataIntegralId");
            return (Criteria) this;
        }

        public Criteria andLeiDataIntegralIdNotBetween(String value1, String value2) {
            addCriterion("lei_data_integral_id not between", value1, value2, "leiDataIntegralId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_integral
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}