package org.ys.crawler.model;

import java.io.Serializable;

public class FootballPlayer implements Serializable {
    private static final long serialVersionUID = -8176442167403580520L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.football_player_id
     *
     * @mbg.generated
     */
    private String footballPlayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.football_player_name
     *
     * @mbg.generated
     */
    private String footballPlayerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.football_team_id
     *
     * @mbg.generated
     */
    private String footballTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.active_flag
     *
     * @mbg.generated
     */
    private Boolean activeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.football_player_type
     *
     * @mbg.generated
     */
    private String footballPlayerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_player.entity_id
     *
     * @mbg.generated
     */
    private String entityId;

    // 非数据库字段,联赛名称
    private String teamName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.football_player_id
     *
     * @return the value of cr_football_player.football_player_id
     *
     * @mbg.generated
     */
    public String getFootballPlayerId() {
        return footballPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.football_player_id
     *
     * @param footballPlayerId the value for cr_football_player.football_player_id
     *
     * @mbg.generated
     */
    public void setFootballPlayerId(String footballPlayerId) {
        this.footballPlayerId = footballPlayerId == null ? null : footballPlayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.football_player_name
     *
     * @return the value of cr_football_player.football_player_name
     *
     * @mbg.generated
     */
    public String getFootballPlayerName() {
        return footballPlayerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.football_player_name
     *
     * @param footballPlayerName the value for cr_football_player.football_player_name
     *
     * @mbg.generated
     */
    public void setFootballPlayerName(String footballPlayerName) {
        this.footballPlayerName = footballPlayerName == null ? null : footballPlayerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.football_team_id
     *
     * @return the value of cr_football_player.football_team_id
     *
     * @mbg.generated
     */
    public String getFootballTeamId() {
        return footballTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.football_team_id
     *
     * @param footballTeamId the value for cr_football_player.football_team_id
     *
     * @mbg.generated
     */
    public void setFootballTeamId(String footballTeamId) {
        this.footballTeamId = footballTeamId == null ? null : footballTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.active_flag
     *
     * @return the value of cr_football_player.active_flag
     *
     * @mbg.generated
     */
    public Boolean getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.active_flag
     *
     * @param activeFlag the value for cr_football_player.active_flag
     *
     * @mbg.generated
     */
    public void setActiveFlag(Boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.football_player_type
     *
     * @return the value of cr_football_player.football_player_type
     *
     * @mbg.generated
     */
    public String getFootballPlayerType() {
        return footballPlayerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.football_player_type
     *
     * @param footballPlayerType the value for cr_football_player.football_player_type
     *
     * @mbg.generated
     */
    public void setFootballPlayerType(String footballPlayerType) {
        this.footballPlayerType = footballPlayerType == null ? null : footballPlayerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_player.entity_id
     *
     * @return the value of cr_football_player.entity_id
     *
     * @mbg.generated
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_player.entity_id
     *
     * @param entityId the value for cr_football_player.entity_id
     *
     * @mbg.generated
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballPlayer other = (FootballPlayer) that;
        return (this.getFootballPlayerId() == null ? other.getFootballPlayerId() == null : this.getFootballPlayerId().equals(other.getFootballPlayerId()))
            && (this.getFootballPlayerName() == null ? other.getFootballPlayerName() == null : this.getFootballPlayerName().equals(other.getFootballPlayerName()))
            && (this.getFootballTeamId() == null ? other.getFootballTeamId() == null : this.getFootballTeamId().equals(other.getFootballTeamId()))
            && (this.getActiveFlag() == null ? other.getActiveFlag() == null : this.getActiveFlag().equals(other.getActiveFlag()))
            && (this.getFootballPlayerType() == null ? other.getFootballPlayerType() == null : this.getFootballPlayerType().equals(other.getFootballPlayerType()))
            && (this.getEntityId() == null ? other.getEntityId() == null : this.getEntityId().equals(other.getEntityId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballPlayerId() == null) ? 0 : getFootballPlayerId().hashCode());
        result = prime * result + ((getFootballPlayerName() == null) ? 0 : getFootballPlayerName().hashCode());
        result = prime * result + ((getFootballTeamId() == null) ? 0 : getFootballTeamId().hashCode());
        result = prime * result + ((getActiveFlag() == null) ? 0 : getActiveFlag().hashCode());
        result = prime * result + ((getFootballPlayerType() == null) ? 0 : getFootballPlayerType().hashCode());
        result = prime * result + ((getEntityId() == null) ? 0 : getEntityId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballPlayerId=").append(footballPlayerId);
        sb.append(", footballPlayerName=").append(footballPlayerName);
        sb.append(", footballTeamId=").append(footballTeamId);
        sb.append(", activeFlag=").append(activeFlag);
        sb.append(", footballPlayerType=").append(footballPlayerType);
        sb.append(", entityId=").append(entityId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}