package org.ys.crawler.model;

import java.util.ArrayList;
import java.util.List;

public class FootballPlayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public FootballPlayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFootballPlayerIdIsNull() {
            addCriterion("football_player_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdIsNotNull() {
            addCriterion("football_player_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdEqualTo(String value) {
            addCriterion("football_player_id =", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdNotEqualTo(String value) {
            addCriterion("football_player_id <>", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdGreaterThan(String value) {
            addCriterion("football_player_id >", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_player_id >=", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdLessThan(String value) {
            addCriterion("football_player_id <", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdLessThanOrEqualTo(String value) {
            addCriterion("football_player_id <=", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdLike(String value) {
            addCriterion("football_player_id like", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdNotLike(String value) {
            addCriterion("football_player_id not like", value, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdIn(List<String> values) {
            addCriterion("football_player_id in", values, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdNotIn(List<String> values) {
            addCriterion("football_player_id not in", values, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdBetween(String value1, String value2) {
            addCriterion("football_player_id between", value1, value2, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerIdNotBetween(String value1, String value2) {
            addCriterion("football_player_id not between", value1, value2, "footballPlayerId");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameIsNull() {
            addCriterion("football_player_name is null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameIsNotNull() {
            addCriterion("football_player_name is not null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameEqualTo(String value) {
            addCriterion("football_player_name =", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameNotEqualTo(String value) {
            addCriterion("football_player_name <>", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameGreaterThan(String value) {
            addCriterion("football_player_name >", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameGreaterThanOrEqualTo(String value) {
            addCriterion("football_player_name >=", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameLessThan(String value) {
            addCriterion("football_player_name <", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameLessThanOrEqualTo(String value) {
            addCriterion("football_player_name <=", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameLike(String value) {
            addCriterion("football_player_name like", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameNotLike(String value) {
            addCriterion("football_player_name not like", value, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameIn(List<String> values) {
            addCriterion("football_player_name in", values, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameNotIn(List<String> values) {
            addCriterion("football_player_name not in", values, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameBetween(String value1, String value2) {
            addCriterion("football_player_name between", value1, value2, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerNameNotBetween(String value1, String value2) {
            addCriterion("football_player_name not between", value1, value2, "footballPlayerName");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIsNull() {
            addCriterion("football_team_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIsNotNull() {
            addCriterion("football_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdEqualTo(String value) {
            addCriterion("football_team_id =", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotEqualTo(String value) {
            addCriterion("football_team_id <>", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdGreaterThan(String value) {
            addCriterion("football_team_id >", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_team_id >=", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLessThan(String value) {
            addCriterion("football_team_id <", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLessThanOrEqualTo(String value) {
            addCriterion("football_team_id <=", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdLike(String value) {
            addCriterion("football_team_id like", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotLike(String value) {
            addCriterion("football_team_id not like", value, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdIn(List<String> values) {
            addCriterion("football_team_id in", values, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotIn(List<String> values) {
            addCriterion("football_team_id not in", values, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdBetween(String value1, String value2) {
            addCriterion("football_team_id between", value1, value2, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andFootballTeamIdNotBetween(String value1, String value2) {
            addCriterion("football_team_id not between", value1, value2, "footballTeamId");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIsNull() {
            addCriterion("active_flag is null");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIsNotNull() {
            addCriterion("active_flag is not null");
            return (Criteria) this;
        }

        public Criteria andActiveFlagEqualTo(Boolean value) {
            addCriterion("active_flag =", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotEqualTo(Boolean value) {
            addCriterion("active_flag <>", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagGreaterThan(Boolean value) {
            addCriterion("active_flag >", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("active_flag >=", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagLessThan(Boolean value) {
            addCriterion("active_flag <", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("active_flag <=", value, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagIn(List<Boolean> values) {
            addCriterion("active_flag in", values, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotIn(List<Boolean> values) {
            addCriterion("active_flag not in", values, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("active_flag between", value1, value2, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andActiveFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("active_flag not between", value1, value2, "activeFlag");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeIsNull() {
            addCriterion("football_player_type is null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeIsNotNull() {
            addCriterion("football_player_type is not null");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeEqualTo(String value) {
            addCriterion("football_player_type =", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeNotEqualTo(String value) {
            addCriterion("football_player_type <>", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeGreaterThan(String value) {
            addCriterion("football_player_type >", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("football_player_type >=", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeLessThan(String value) {
            addCriterion("football_player_type <", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeLessThanOrEqualTo(String value) {
            addCriterion("football_player_type <=", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeLike(String value) {
            addCriterion("football_player_type like", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeNotLike(String value) {
            addCriterion("football_player_type not like", value, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeIn(List<String> values) {
            addCriterion("football_player_type in", values, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeNotIn(List<String> values) {
            addCriterion("football_player_type not in", values, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeBetween(String value1, String value2) {
            addCriterion("football_player_type between", value1, value2, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andFootballPlayerTypeNotBetween(String value1, String value2) {
            addCriterion("football_player_type not between", value1, value2, "footballPlayerType");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNull() {
            addCriterion("entity_id is null");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNotNull() {
            addCriterion("entity_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntityIdEqualTo(String value) {
            addCriterion("entity_id =", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotEqualTo(String value) {
            addCriterion("entity_id <>", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThan(String value) {
            addCriterion("entity_id >", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThanOrEqualTo(String value) {
            addCriterion("entity_id >=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThan(String value) {
            addCriterion("entity_id <", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThanOrEqualTo(String value) {
            addCriterion("entity_id <=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLike(String value) {
            addCriterion("entity_id like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotLike(String value) {
            addCriterion("entity_id not like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIn(List<String> values) {
            addCriterion("entity_id in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotIn(List<String> values) {
            addCriterion("entity_id not in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdBetween(String value1, String value2) {
            addCriterion("entity_id between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotBetween(String value1, String value2) {
            addCriterion("entity_id not between", value1, value2, "entityId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_player
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_player
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}