package org.ys.crawler.model;

import java.io.Serializable;

public class FootballSeasonCategory implements Serializable {
    private static final long serialVersionUID = 7595944911511944013L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season_category.football_season_category_id
     *
     * @mbg.generated
     */
    private String footballSeasonCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season_category.football_season_category_name
     *
     * @mbg.generated
     */
    private String footballSeasonCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season_category.football_season_category_url
     *
     * @mbg.generated
     */
    private String footballSeasonCategoryUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season_category.football_season_id
     *
     * @mbg.generated
     */
    private String footballSeasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season_category.round_count
     *
     * @mbg.generated
     */
    private Integer roundCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season_category.football_season_category_id
     *
     * @return the value of cr_football_season_category.football_season_category_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonCategoryId() {
        return footballSeasonCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season_category.football_season_category_id
     *
     * @param footballSeasonCategoryId the value for cr_football_season_category.football_season_category_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonCategoryId(String footballSeasonCategoryId) {
        this.footballSeasonCategoryId = footballSeasonCategoryId == null ? null : footballSeasonCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season_category.football_season_category_name
     *
     * @return the value of cr_football_season_category.football_season_category_name
     *
     * @mbg.generated
     */
    public String getFootballSeasonCategoryName() {
        return footballSeasonCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season_category.football_season_category_name
     *
     * @param footballSeasonCategoryName the value for cr_football_season_category.football_season_category_name
     *
     * @mbg.generated
     */
    public void setFootballSeasonCategoryName(String footballSeasonCategoryName) {
        this.footballSeasonCategoryName = footballSeasonCategoryName == null ? null : footballSeasonCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season_category.football_season_category_url
     *
     * @return the value of cr_football_season_category.football_season_category_url
     *
     * @mbg.generated
     */
    public String getFootballSeasonCategoryUrl() {
        return footballSeasonCategoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season_category.football_season_category_url
     *
     * @param footballSeasonCategoryUrl the value for cr_football_season_category.football_season_category_url
     *
     * @mbg.generated
     */
    public void setFootballSeasonCategoryUrl(String footballSeasonCategoryUrl) {
        this.footballSeasonCategoryUrl = footballSeasonCategoryUrl == null ? null : footballSeasonCategoryUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season_category.football_season_id
     *
     * @return the value of cr_football_season_category.football_season_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonId() {
        return footballSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season_category.football_season_id
     *
     * @param footballSeasonId the value for cr_football_season_category.football_season_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonId(String footballSeasonId) {
        this.footballSeasonId = footballSeasonId == null ? null : footballSeasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season_category.round_count
     *
     * @return the value of cr_football_season_category.round_count
     *
     * @mbg.generated
     */
    public Integer getRoundCount() {
        return roundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season_category.round_count
     *
     * @param roundCount the value for cr_football_season_category.round_count
     *
     * @mbg.generated
     */
    public void setRoundCount(Integer roundCount) {
        this.roundCount = roundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballSeasonCategory other = (FootballSeasonCategory) that;
        return (this.getFootballSeasonCategoryId() == null ? other.getFootballSeasonCategoryId() == null : this.getFootballSeasonCategoryId().equals(other.getFootballSeasonCategoryId()))
            && (this.getFootballSeasonCategoryName() == null ? other.getFootballSeasonCategoryName() == null : this.getFootballSeasonCategoryName().equals(other.getFootballSeasonCategoryName()))
            && (this.getFootballSeasonCategoryUrl() == null ? other.getFootballSeasonCategoryUrl() == null : this.getFootballSeasonCategoryUrl().equals(other.getFootballSeasonCategoryUrl()))
            && (this.getFootballSeasonId() == null ? other.getFootballSeasonId() == null : this.getFootballSeasonId().equals(other.getFootballSeasonId()))
            && (this.getRoundCount() == null ? other.getRoundCount() == null : this.getRoundCount().equals(other.getRoundCount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballSeasonCategoryId() == null) ? 0 : getFootballSeasonCategoryId().hashCode());
        result = prime * result + ((getFootballSeasonCategoryName() == null) ? 0 : getFootballSeasonCategoryName().hashCode());
        result = prime * result + ((getFootballSeasonCategoryUrl() == null) ? 0 : getFootballSeasonCategoryUrl().hashCode());
        result = prime * result + ((getFootballSeasonId() == null) ? 0 : getFootballSeasonId().hashCode());
        result = prime * result + ((getRoundCount() == null) ? 0 : getRoundCount().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballSeasonCategoryId=").append(footballSeasonCategoryId);
        sb.append(", footballSeasonCategoryName=").append(footballSeasonCategoryName);
        sb.append(", footballSeasonCategoryUrl=").append(footballSeasonCategoryUrl);
        sb.append(", footballSeasonId=").append(footballSeasonId);
        sb.append(", roundCount=").append(roundCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}