package org.ys.crawler.model;

import java.util.ArrayList;
import java.util.List;

public class FootballSeasonCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public FootballSeasonCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFootballSeasonCategoryIdIsNull() {
            addCriterion("football_season_category_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIsNotNull() {
            addCriterion("football_season_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdEqualTo(String value) {
            addCriterion("football_season_category_id =", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotEqualTo(String value) {
            addCriterion("football_season_category_id <>", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThan(String value) {
            addCriterion("football_season_category_id >", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_category_id >=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThan(String value) {
            addCriterion("football_season_category_id <", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_category_id <=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLike(String value) {
            addCriterion("football_season_category_id like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotLike(String value) {
            addCriterion("football_season_category_id not like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIn(List<String> values) {
            addCriterion("football_season_category_id in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotIn(List<String> values) {
            addCriterion("football_season_category_id not in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdBetween(String value1, String value2) {
            addCriterion("football_season_category_id between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotBetween(String value1, String value2) {
            addCriterion("football_season_category_id not between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameIsNull() {
            addCriterion("football_season_category_name is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameIsNotNull() {
            addCriterion("football_season_category_name is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameEqualTo(String value) {
            addCriterion("football_season_category_name =", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameNotEqualTo(String value) {
            addCriterion("football_season_category_name <>", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameGreaterThan(String value) {
            addCriterion("football_season_category_name >", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_category_name >=", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameLessThan(String value) {
            addCriterion("football_season_category_name <", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("football_season_category_name <=", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameLike(String value) {
            addCriterion("football_season_category_name like", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameNotLike(String value) {
            addCriterion("football_season_category_name not like", value, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameIn(List<String> values) {
            addCriterion("football_season_category_name in", values, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameNotIn(List<String> values) {
            addCriterion("football_season_category_name not in", values, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameBetween(String value1, String value2) {
            addCriterion("football_season_category_name between", value1, value2, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryNameNotBetween(String value1, String value2) {
            addCriterion("football_season_category_name not between", value1, value2, "footballSeasonCategoryName");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlIsNull() {
            addCriterion("football_season_category_url is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlIsNotNull() {
            addCriterion("football_season_category_url is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlEqualTo(String value) {
            addCriterion("football_season_category_url =", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlNotEqualTo(String value) {
            addCriterion("football_season_category_url <>", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlGreaterThan(String value) {
            addCriterion("football_season_category_url >", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_category_url >=", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlLessThan(String value) {
            addCriterion("football_season_category_url <", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlLessThanOrEqualTo(String value) {
            addCriterion("football_season_category_url <=", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlLike(String value) {
            addCriterion("football_season_category_url like", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlNotLike(String value) {
            addCriterion("football_season_category_url not like", value, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlIn(List<String> values) {
            addCriterion("football_season_category_url in", values, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlNotIn(List<String> values) {
            addCriterion("football_season_category_url not in", values, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlBetween(String value1, String value2) {
            addCriterion("football_season_category_url between", value1, value2, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryUrlNotBetween(String value1, String value2) {
            addCriterion("football_season_category_url not between", value1, value2, "footballSeasonCategoryUrl");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNull() {
            addCriterion("football_season_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNotNull() {
            addCriterion("football_season_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdEqualTo(String value) {
            addCriterion("football_season_id =", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotEqualTo(String value) {
            addCriterion("football_season_id <>", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThan(String value) {
            addCriterion("football_season_id >", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_id >=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThan(String value) {
            addCriterion("football_season_id <", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_id <=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLike(String value) {
            addCriterion("football_season_id like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotLike(String value) {
            addCriterion("football_season_id not like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIn(List<String> values) {
            addCriterion("football_season_id in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotIn(List<String> values) {
            addCriterion("football_season_id not in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdBetween(String value1, String value2) {
            addCriterion("football_season_id between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotBetween(String value1, String value2) {
            addCriterion("football_season_id not between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andRoundCountIsNull() {
            addCriterion("round_count is null");
            return (Criteria) this;
        }

        public Criteria andRoundCountIsNotNull() {
            addCriterion("round_count is not null");
            return (Criteria) this;
        }

        public Criteria andRoundCountEqualTo(Integer value) {
            addCriterion("round_count =", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountNotEqualTo(Integer value) {
            addCriterion("round_count <>", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountGreaterThan(Integer value) {
            addCriterion("round_count >", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("round_count >=", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountLessThan(Integer value) {
            addCriterion("round_count <", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountLessThanOrEqualTo(Integer value) {
            addCriterion("round_count <=", value, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountIn(List<Integer> values) {
            addCriterion("round_count in", values, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountNotIn(List<Integer> values) {
            addCriterion("round_count not in", values, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountBetween(Integer value1, Integer value2) {
            addCriterion("round_count between", value1, value2, "roundCount");
            return (Criteria) this;
        }

        public Criteria andRoundCountNotBetween(Integer value1, Integer value2) {
            addCriterion("round_count not between", value1, value2, "roundCount");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNull() {
            addCriterion("football_league_match_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNotNull() {
            addCriterion("football_league_match_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdEqualTo(String value) {
            addCriterion("football_league_match_id =", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotEqualTo(String value) {
            addCriterion("football_league_match_id <>", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThan(String value) {
            addCriterion("football_league_match_id >", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_id >=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThan(String value) {
            addCriterion("football_league_match_id <", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_id <=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLike(String value) {
            addCriterion("football_league_match_id like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotLike(String value) {
            addCriterion("football_league_match_id not like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIn(List<String> values) {
            addCriterion("football_league_match_id in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotIn(List<String> values) {
            addCriterion("football_league_match_id not in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdBetween(String value1, String value2) {
            addCriterion("football_league_match_id between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotBetween(String value1, String value2) {
            addCriterion("football_league_match_id not between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_season_category
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}