package org.ys.crawler.model;

import java.util.ArrayList;
import java.util.List;

public class FootballLeagueMatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public FootballLeagueMatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFootballLeagueMatchIdIsNull() {
            addCriterion("football_league_match_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNotNull() {
            addCriterion("football_league_match_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdEqualTo(String value) {
            addCriterion("football_league_match_id =", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotEqualTo(String value) {
            addCriterion("football_league_match_id <>", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThan(String value) {
            addCriterion("football_league_match_id >", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_id >=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThan(String value) {
            addCriterion("football_league_match_id <", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_id <=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLike(String value) {
            addCriterion("football_league_match_id like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotLike(String value) {
            addCriterion("football_league_match_id not like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIn(List<String> values) {
            addCriterion("football_league_match_id in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotIn(List<String> values) {
            addCriterion("football_league_match_id not in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdBetween(String value1, String value2) {
            addCriterion("football_league_match_id between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotBetween(String value1, String value2) {
            addCriterion("football_league_match_id not between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameIsNull() {
            addCriterion("football_league_match_name is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameIsNotNull() {
            addCriterion("football_league_match_name is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameEqualTo(String value) {
            addCriterion("football_league_match_name =", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameNotEqualTo(String value) {
            addCriterion("football_league_match_name <>", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameGreaterThan(String value) {
            addCriterion("football_league_match_name >", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_name >=", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameLessThan(String value) {
            addCriterion("football_league_match_name <", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_name <=", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameLike(String value) {
            addCriterion("football_league_match_name like", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameNotLike(String value) {
            addCriterion("football_league_match_name not like", value, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameIn(List<String> values) {
            addCriterion("football_league_match_name in", values, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameNotIn(List<String> values) {
            addCriterion("football_league_match_name not in", values, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameBetween(String value1, String value2) {
            addCriterion("football_league_match_name between", value1, value2, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchNameNotBetween(String value1, String value2) {
            addCriterion("football_league_match_name not between", value1, value2, "footballLeagueMatchName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNull() {
            addCriterion("region_name is null");
            return (Criteria) this;
        }

        public Criteria andRegionNameIsNotNull() {
            addCriterion("region_name is not null");
            return (Criteria) this;
        }

        public Criteria andRegionNameEqualTo(String value) {
            addCriterion("region_name =", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotEqualTo(String value) {
            addCriterion("region_name <>", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThan(String value) {
            addCriterion("region_name >", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameGreaterThanOrEqualTo(String value) {
            addCriterion("region_name >=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThan(String value) {
            addCriterion("region_name <", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLessThanOrEqualTo(String value) {
            addCriterion("region_name <=", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameLike(String value) {
            addCriterion("region_name like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotLike(String value) {
            addCriterion("region_name not like", value, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameIn(List<String> values) {
            addCriterion("region_name in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotIn(List<String> values) {
            addCriterion("region_name not in", values, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameBetween(String value1, String value2) {
            addCriterion("region_name between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andRegionNameNotBetween(String value1, String value2) {
            addCriterion("region_name not between", value1, value2, "regionName");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelIsNull() {
            addCriterion("football_league_match_level is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelIsNotNull() {
            addCriterion("football_league_match_level is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelEqualTo(String value) {
            addCriterion("football_league_match_level =", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelNotEqualTo(String value) {
            addCriterion("football_league_match_level <>", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelGreaterThan(String value) {
            addCriterion("football_league_match_level >", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_level >=", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelLessThan(String value) {
            addCriterion("football_league_match_level <", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_level <=", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelLike(String value) {
            addCriterion("football_league_match_level like", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelNotLike(String value) {
            addCriterion("football_league_match_level not like", value, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelIn(List<String> values) {
            addCriterion("football_league_match_level in", values, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelNotIn(List<String> values) {
            addCriterion("football_league_match_level not in", values, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelBetween(String value1, String value2) {
            addCriterion("football_league_match_level between", value1, value2, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchLevelNotBetween(String value1, String value2) {
            addCriterion("football_league_match_level not between", value1, value2, "footballLeagueMatchLevel");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlIsNull() {
            addCriterion("league_match_url is null");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlIsNotNull() {
            addCriterion("league_match_url is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlEqualTo(String value) {
            addCriterion("league_match_url =", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlNotEqualTo(String value) {
            addCriterion("league_match_url <>", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlGreaterThan(String value) {
            addCriterion("league_match_url >", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlGreaterThanOrEqualTo(String value) {
            addCriterion("league_match_url >=", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlLessThan(String value) {
            addCriterion("league_match_url <", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlLessThanOrEqualTo(String value) {
            addCriterion("league_match_url <=", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlLike(String value) {
            addCriterion("league_match_url like", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlNotLike(String value) {
            addCriterion("league_match_url not like", value, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlIn(List<String> values) {
            addCriterion("league_match_url in", values, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlNotIn(List<String> values) {
            addCriterion("league_match_url not in", values, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlBetween(String value1, String value2) {
            addCriterion("league_match_url between", value1, value2, "leagueMatchUrl");
            return (Criteria) this;
        }

        public Criteria andLeagueMatchUrlNotBetween(String value1, String value2) {
            addCriterion("league_match_url not between", value1, value2, "leagueMatchUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_league_match
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}