package org.ys.crawler.model;

import java.io.Serializable;
import java.util.Date;

public class FootballSeason implements Serializable {
    private static final long serialVersionUID = 4965160020506729912L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.football_season_id
     *
     * @mbg.generated
     */
    private String footballSeasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.football_season_name
     *
     * @mbg.generated
     */
    private String footballSeasonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.football_season_url
     *
     * @mbg.generated
     */
    private String footballSeasonUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.football_league_match_id
     *
     * @mbg.generated
     */
    private String footballLeagueMatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.season_begin_date
     *
     * @mbg.generated
     */
    private Date seasonBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_season.season_end_date
     *
     * @mbg.generated
     */
    private Date seasonEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.football_season_id
     *
     * @return the value of cr_football_season.football_season_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonId() {
        return footballSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.football_season_id
     *
     * @param footballSeasonId the value for cr_football_season.football_season_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonId(String footballSeasonId) {
        this.footballSeasonId = footballSeasonId == null ? null : footballSeasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.football_season_name
     *
     * @return the value of cr_football_season.football_season_name
     *
     * @mbg.generated
     */
    public String getFootballSeasonName() {
        return footballSeasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.football_season_name
     *
     * @param footballSeasonName the value for cr_football_season.football_season_name
     *
     * @mbg.generated
     */
    public void setFootballSeasonName(String footballSeasonName) {
        this.footballSeasonName = footballSeasonName == null ? null : footballSeasonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.football_season_url
     *
     * @return the value of cr_football_season.football_season_url
     *
     * @mbg.generated
     */
    public String getFootballSeasonUrl() {
        return footballSeasonUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.football_season_url
     *
     * @param footballSeasonUrl the value for cr_football_season.football_season_url
     *
     * @mbg.generated
     */
    public void setFootballSeasonUrl(String footballSeasonUrl) {
        this.footballSeasonUrl = footballSeasonUrl == null ? null : footballSeasonUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.football_league_match_id
     *
     * @return the value of cr_football_season.football_league_match_id
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchId() {
        return footballLeagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.football_league_match_id
     *
     * @param footballLeagueMatchId the value for cr_football_season.football_league_match_id
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchId(String footballLeagueMatchId) {
        this.footballLeagueMatchId = footballLeagueMatchId == null ? null : footballLeagueMatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.season_begin_date
     *
     * @return the value of cr_football_season.season_begin_date
     *
     * @mbg.generated
     */
    public Date getSeasonBeginDate() {
        return seasonBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.season_begin_date
     *
     * @param seasonBeginDate the value for cr_football_season.season_begin_date
     *
     * @mbg.generated
     */
    public void setSeasonBeginDate(Date seasonBeginDate) {
        this.seasonBeginDate = seasonBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_season.season_end_date
     *
     * @return the value of cr_football_season.season_end_date
     *
     * @mbg.generated
     */
    public Date getSeasonEndDate() {
        return seasonEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_season.season_end_date
     *
     * @param seasonEndDate the value for cr_football_season.season_end_date
     *
     * @mbg.generated
     */
    public void setSeasonEndDate(Date seasonEndDate) {
        this.seasonEndDate = seasonEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballSeason other = (FootballSeason) that;
        return (this.getFootballSeasonId() == null ? other.getFootballSeasonId() == null : this.getFootballSeasonId().equals(other.getFootballSeasonId()))
            && (this.getFootballSeasonName() == null ? other.getFootballSeasonName() == null : this.getFootballSeasonName().equals(other.getFootballSeasonName()))
            && (this.getFootballSeasonUrl() == null ? other.getFootballSeasonUrl() == null : this.getFootballSeasonUrl().equals(other.getFootballSeasonUrl()))
            && (this.getFootballLeagueMatchId() == null ? other.getFootballLeagueMatchId() == null : this.getFootballLeagueMatchId().equals(other.getFootballLeagueMatchId()))
            && (this.getSeasonBeginDate() == null ? other.getSeasonBeginDate() == null : this.getSeasonBeginDate().equals(other.getSeasonBeginDate()))
            && (this.getSeasonEndDate() == null ? other.getSeasonEndDate() == null : this.getSeasonEndDate().equals(other.getSeasonEndDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballSeasonId() == null) ? 0 : getFootballSeasonId().hashCode());
        result = prime * result + ((getFootballSeasonName() == null) ? 0 : getFootballSeasonName().hashCode());
        result = prime * result + ((getFootballSeasonUrl() == null) ? 0 : getFootballSeasonUrl().hashCode());
        result = prime * result + ((getFootballLeagueMatchId() == null) ? 0 : getFootballLeagueMatchId().hashCode());
        result = prime * result + ((getSeasonBeginDate() == null) ? 0 : getSeasonBeginDate().hashCode());
        result = prime * result + ((getSeasonEndDate() == null) ? 0 : getSeasonEndDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballSeasonId=").append(footballSeasonId);
        sb.append(", footballSeasonName=").append(footballSeasonName);
        sb.append(", footballSeasonUrl=").append(footballSeasonUrl);
        sb.append(", footballLeagueMatchId=").append(footballLeagueMatchId);
        sb.append(", seasonBeginDate=").append(seasonBeginDate);
        sb.append(", seasonEndDate=").append(seasonEndDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}