package org.ys.crawler.model;

import java.io.Serializable;

public class FootballLeagueMatch implements Serializable {
    private static final long serialVersionUID = -2295543969689378264L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_league_match.football_league_match_id
     *
     * @mbg.generated
     */
    private String footballLeagueMatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_league_match.football_league_match_name
     *
     * @mbg.generated
     */
    private String footballLeagueMatchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_league_match.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_league_match.football_league_match_level
     *
     * @mbg.generated
     */
    private String footballLeagueMatchLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_league_match.league_match_url
     *
     * @mbg.generated
     */
    private String leagueMatchUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_league_match.football_league_match_id
     *
     * @return the value of cr_football_league_match.football_league_match_id
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchId() {
        return footballLeagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_league_match.football_league_match_id
     *
     * @param footballLeagueMatchId the value for cr_football_league_match.football_league_match_id
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchId(String footballLeagueMatchId) {
        this.footballLeagueMatchId = footballLeagueMatchId == null ? null : footballLeagueMatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_league_match.football_league_match_name
     *
     * @return the value of cr_football_league_match.football_league_match_name
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchName() {
        return footballLeagueMatchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_league_match.football_league_match_name
     *
     * @param footballLeagueMatchName the value for cr_football_league_match.football_league_match_name
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchName(String footballLeagueMatchName) {
        this.footballLeagueMatchName = footballLeagueMatchName == null ? null : footballLeagueMatchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_league_match.region_name
     *
     * @return the value of cr_football_league_match.region_name
     *
     * @mbg.generated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_league_match.region_name
     *
     * @param regionName the value for cr_football_league_match.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_league_match.football_league_match_level
     *
     * @return the value of cr_football_league_match.football_league_match_level
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchLevel() {
        return footballLeagueMatchLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_league_match.football_league_match_level
     *
     * @param footballLeagueMatchLevel the value for cr_football_league_match.football_league_match_level
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchLevel(String footballLeagueMatchLevel) {
        this.footballLeagueMatchLevel = footballLeagueMatchLevel == null ? null : footballLeagueMatchLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_league_match.league_match_url
     *
     * @return the value of cr_football_league_match.league_match_url
     *
     * @mbg.generated
     */
    public String getLeagueMatchUrl() {
        return leagueMatchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_league_match.league_match_url
     *
     * @param leagueMatchUrl the value for cr_football_league_match.league_match_url
     *
     * @mbg.generated
     */
    public void setLeagueMatchUrl(String leagueMatchUrl) {
        this.leagueMatchUrl = leagueMatchUrl == null ? null : leagueMatchUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballLeagueMatch other = (FootballLeagueMatch) that;
        return (this.getFootballLeagueMatchId() == null ? other.getFootballLeagueMatchId() == null : this.getFootballLeagueMatchId().equals(other.getFootballLeagueMatchId()))
            && (this.getFootballLeagueMatchName() == null ? other.getFootballLeagueMatchName() == null : this.getFootballLeagueMatchName().equals(other.getFootballLeagueMatchName()))
            && (this.getRegionName() == null ? other.getRegionName() == null : this.getRegionName().equals(other.getRegionName()))
            && (this.getFootballLeagueMatchLevel() == null ? other.getFootballLeagueMatchLevel() == null : this.getFootballLeagueMatchLevel().equals(other.getFootballLeagueMatchLevel()))
            && (this.getLeagueMatchUrl() == null ? other.getLeagueMatchUrl() == null : this.getLeagueMatchUrl().equals(other.getLeagueMatchUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballLeagueMatchId() == null) ? 0 : getFootballLeagueMatchId().hashCode());
        result = prime * result + ((getFootballLeagueMatchName() == null) ? 0 : getFootballLeagueMatchName().hashCode());
        result = prime * result + ((getRegionName() == null) ? 0 : getRegionName().hashCode());
        result = prime * result + ((getFootballLeagueMatchLevel() == null) ? 0 : getFootballLeagueMatchLevel().hashCode());
        result = prime * result + ((getLeagueMatchUrl() == null) ? 0 : getLeagueMatchUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_league_match
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballLeagueMatchId=").append(footballLeagueMatchId);
        sb.append(", footballLeagueMatchName=").append(footballLeagueMatchName);
        sb.append(", regionName=").append(regionName);
        sb.append(", footballLeagueMatchLevel=").append(footballLeagueMatchLevel);
        sb.append(", leagueMatchUrl=").append(leagueMatchUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}