package org.ys.crawler.model;

import java.io.Serializable;

public class FootballIntegral implements Serializable {
    private static final long serialVersionUID = -3911642329352590529L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.football_integral_id
     *
     * @mbg.generated
     */
    private String footballIntegralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.football_league_match_id
     *
     * @mbg.generated
     */
    private String footballLeagueMatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.football_season_id
     *
     * @mbg.generated
     */
    private String footballSeasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.football_season_category_id
     *
     * @mbg.generated
     */
    private String footballSeasonCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.football_team_id
     *
     * @mbg.generated
     */
    private String footballTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.integral_total
     *
     * @mbg.generated
     */
    private Integer integralTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.goal_total
     *
     * @mbg.generated
     */
    private Integer goalTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.fumble_total
     *
     * @mbg.generated
     */
    private Integer fumbleTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.difference_total
     *
     * @mbg.generated
     */
    private Integer differenceTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.played_total
     *
     * @mbg.generated
     */
    private Integer playedTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.win_total
     *
     * @mbg.generated
     */
    private Integer winTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.draw_total
     *
     * @mbg.generated
     */
    private Integer drawTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.lost_total
     *
     * @mbg.generated
     */
    private Integer lostTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.goal_per_played
     *
     * @mbg.generated
     */
    private Float goalPerPlayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.fumble_per_played
     *
     * @mbg.generated
     */
    private Float fumblePerPlayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.win_per_played
     *
     * @mbg.generated
     */
    private Float winPerPlayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.win_home
     *
     * @mbg.generated
     */
    private Integer winHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.win_away
     *
     * @mbg.generated
     */
    private Integer winAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.draw_home
     *
     * @mbg.generated
     */
    private Integer drawHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.draw_away
     *
     * @mbg.generated
     */
    private Integer drawAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.lost_home
     *
     * @mbg.generated
     */
    private Integer lostHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.lost_away
     *
     * @mbg.generated
     */
    private Integer lostAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.goal_home
     *
     * @mbg.generated
     */
    private Integer goalHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.goal_away
     *
     * @mbg.generated
     */
    private Integer goalAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.fumble_home
     *
     * @mbg.generated
     */
    private Integer fumbleHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.fumble_away
     *
     * @mbg.generated
     */
    private Integer fumbleAway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_integral.lei_data_integral_id
     *
     * @mbg.generated
     */
    private String leiDataIntegralId;

    // 非数据库字段,球队名称
    private String teamName;
    // 非数据库字段,联赛名称
    private String footballLeagueMatchName;
    // 非数据库字段,联赛赛季名称
    private String footballSeasonName;
    // 非数据库字段,联赛赛季类别名称
    private String footballSeasonCategoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.football_integral_id
     *
     * @return the value of cr_football_integral.football_integral_id
     *
     * @mbg.generated
     */
    public String getFootballIntegralId() {
        return footballIntegralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.football_integral_id
     *
     * @param footballIntegralId the value for cr_football_integral.football_integral_id
     *
     * @mbg.generated
     */
    public void setFootballIntegralId(String footballIntegralId) {
        this.footballIntegralId = footballIntegralId == null ? null : footballIntegralId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.football_league_match_id
     *
     * @return the value of cr_football_integral.football_league_match_id
     *
     * @mbg.generated
     */
    public String getFootballLeagueMatchId() {
        return footballLeagueMatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.football_league_match_id
     *
     * @param footballLeagueMatchId the value for cr_football_integral.football_league_match_id
     *
     * @mbg.generated
     */
    public void setFootballLeagueMatchId(String footballLeagueMatchId) {
        this.footballLeagueMatchId = footballLeagueMatchId == null ? null : footballLeagueMatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.football_season_id
     *
     * @return the value of cr_football_integral.football_season_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonId() {
        return footballSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.football_season_id
     *
     * @param footballSeasonId the value for cr_football_integral.football_season_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonId(String footballSeasonId) {
        this.footballSeasonId = footballSeasonId == null ? null : footballSeasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.football_season_category_id
     *
     * @return the value of cr_football_integral.football_season_category_id
     *
     * @mbg.generated
     */
    public String getFootballSeasonCategoryId() {
        return footballSeasonCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.football_season_category_id
     *
     * @param footballSeasonCategoryId the value for cr_football_integral.football_season_category_id
     *
     * @mbg.generated
     */
    public void setFootballSeasonCategoryId(String footballSeasonCategoryId) {
        this.footballSeasonCategoryId = footballSeasonCategoryId == null ? null : footballSeasonCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.football_team_id
     *
     * @return the value of cr_football_integral.football_team_id
     *
     * @mbg.generated
     */
    public String getFootballTeamId() {
        return footballTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.football_team_id
     *
     * @param footballTeamId the value for cr_football_integral.football_team_id
     *
     * @mbg.generated
     */
    public void setFootballTeamId(String footballTeamId) {
        this.footballTeamId = footballTeamId == null ? null : footballTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.integral_total
     *
     * @return the value of cr_football_integral.integral_total
     *
     * @mbg.generated
     */
    public Integer getIntegralTotal() {
        return integralTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.integral_total
     *
     * @param integralTotal the value for cr_football_integral.integral_total
     *
     * @mbg.generated
     */
    public void setIntegralTotal(Integer integralTotal) {
        this.integralTotal = integralTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.goal_total
     *
     * @return the value of cr_football_integral.goal_total
     *
     * @mbg.generated
     */
    public Integer getGoalTotal() {
        return goalTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.goal_total
     *
     * @param goalTotal the value for cr_football_integral.goal_total
     *
     * @mbg.generated
     */
    public void setGoalTotal(Integer goalTotal) {
        this.goalTotal = goalTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.fumble_total
     *
     * @return the value of cr_football_integral.fumble_total
     *
     * @mbg.generated
     */
    public Integer getFumbleTotal() {
        return fumbleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.fumble_total
     *
     * @param fumbleTotal the value for cr_football_integral.fumble_total
     *
     * @mbg.generated
     */
    public void setFumbleTotal(Integer fumbleTotal) {
        this.fumbleTotal = fumbleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.difference_total
     *
     * @return the value of cr_football_integral.difference_total
     *
     * @mbg.generated
     */
    public Integer getDifferenceTotal() {
        return differenceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.difference_total
     *
     * @param differenceTotal the value for cr_football_integral.difference_total
     *
     * @mbg.generated
     */
    public void setDifferenceTotal(Integer differenceTotal) {
        this.differenceTotal = differenceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.played_total
     *
     * @return the value of cr_football_integral.played_total
     *
     * @mbg.generated
     */
    public Integer getPlayedTotal() {
        return playedTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.played_total
     *
     * @param playedTotal the value for cr_football_integral.played_total
     *
     * @mbg.generated
     */
    public void setPlayedTotal(Integer playedTotal) {
        this.playedTotal = playedTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.win_total
     *
     * @return the value of cr_football_integral.win_total
     *
     * @mbg.generated
     */
    public Integer getWinTotal() {
        return winTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.win_total
     *
     * @param winTotal the value for cr_football_integral.win_total
     *
     * @mbg.generated
     */
    public void setWinTotal(Integer winTotal) {
        this.winTotal = winTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.draw_total
     *
     * @return the value of cr_football_integral.draw_total
     *
     * @mbg.generated
     */
    public Integer getDrawTotal() {
        return drawTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.draw_total
     *
     * @param drawTotal the value for cr_football_integral.draw_total
     *
     * @mbg.generated
     */
    public void setDrawTotal(Integer drawTotal) {
        this.drawTotal = drawTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.lost_total
     *
     * @return the value of cr_football_integral.lost_total
     *
     * @mbg.generated
     */
    public Integer getLostTotal() {
        return lostTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.lost_total
     *
     * @param lostTotal the value for cr_football_integral.lost_total
     *
     * @mbg.generated
     */
    public void setLostTotal(Integer lostTotal) {
        this.lostTotal = lostTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.goal_per_played
     *
     * @return the value of cr_football_integral.goal_per_played
     *
     * @mbg.generated
     */
    public Float getGoalPerPlayed() {
        return goalPerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.goal_per_played
     *
     * @param goalPerPlayed the value for cr_football_integral.goal_per_played
     *
     * @mbg.generated
     */
    public void setGoalPerPlayed(Float goalPerPlayed) {
        this.goalPerPlayed = goalPerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.fumble_per_played
     *
     * @return the value of cr_football_integral.fumble_per_played
     *
     * @mbg.generated
     */
    public Float getFumblePerPlayed() {
        return fumblePerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.fumble_per_played
     *
     * @param fumblePerPlayed the value for cr_football_integral.fumble_per_played
     *
     * @mbg.generated
     */
    public void setFumblePerPlayed(Float fumblePerPlayed) {
        this.fumblePerPlayed = fumblePerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.win_per_played
     *
     * @return the value of cr_football_integral.win_per_played
     *
     * @mbg.generated
     */
    public Float getWinPerPlayed() {
        return winPerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.win_per_played
     *
     * @param winPerPlayed the value for cr_football_integral.win_per_played
     *
     * @mbg.generated
     */
    public void setWinPerPlayed(Float winPerPlayed) {
        this.winPerPlayed = winPerPlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.win_home
     *
     * @return the value of cr_football_integral.win_home
     *
     * @mbg.generated
     */
    public Integer getWinHome() {
        return winHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.win_home
     *
     * @param winHome the value for cr_football_integral.win_home
     *
     * @mbg.generated
     */
    public void setWinHome(Integer winHome) {
        this.winHome = winHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.win_away
     *
     * @return the value of cr_football_integral.win_away
     *
     * @mbg.generated
     */
    public Integer getWinAway() {
        return winAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.win_away
     *
     * @param winAway the value for cr_football_integral.win_away
     *
     * @mbg.generated
     */
    public void setWinAway(Integer winAway) {
        this.winAway = winAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.draw_home
     *
     * @return the value of cr_football_integral.draw_home
     *
     * @mbg.generated
     */
    public Integer getDrawHome() {
        return drawHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.draw_home
     *
     * @param drawHome the value for cr_football_integral.draw_home
     *
     * @mbg.generated
     */
    public void setDrawHome(Integer drawHome) {
        this.drawHome = drawHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.draw_away
     *
     * @return the value of cr_football_integral.draw_away
     *
     * @mbg.generated
     */
    public Integer getDrawAway() {
        return drawAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.draw_away
     *
     * @param drawAway the value for cr_football_integral.draw_away
     *
     * @mbg.generated
     */
    public void setDrawAway(Integer drawAway) {
        this.drawAway = drawAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.lost_home
     *
     * @return the value of cr_football_integral.lost_home
     *
     * @mbg.generated
     */
    public Integer getLostHome() {
        return lostHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.lost_home
     *
     * @param lostHome the value for cr_football_integral.lost_home
     *
     * @mbg.generated
     */
    public void setLostHome(Integer lostHome) {
        this.lostHome = lostHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.lost_away
     *
     * @return the value of cr_football_integral.lost_away
     *
     * @mbg.generated
     */
    public Integer getLostAway() {
        return lostAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.lost_away
     *
     * @param lostAway the value for cr_football_integral.lost_away
     *
     * @mbg.generated
     */
    public void setLostAway(Integer lostAway) {
        this.lostAway = lostAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.goal_home
     *
     * @return the value of cr_football_integral.goal_home
     *
     * @mbg.generated
     */
    public Integer getGoalHome() {
        return goalHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.goal_home
     *
     * @param goalHome the value for cr_football_integral.goal_home
     *
     * @mbg.generated
     */
    public void setGoalHome(Integer goalHome) {
        this.goalHome = goalHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.goal_away
     *
     * @return the value of cr_football_integral.goal_away
     *
     * @mbg.generated
     */
    public Integer getGoalAway() {
        return goalAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.goal_away
     *
     * @param goalAway the value for cr_football_integral.goal_away
     *
     * @mbg.generated
     */
    public void setGoalAway(Integer goalAway) {
        this.goalAway = goalAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.fumble_home
     *
     * @return the value of cr_football_integral.fumble_home
     *
     * @mbg.generated
     */
    public Integer getFumbleHome() {
        return fumbleHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.fumble_home
     *
     * @param fumbleHome the value for cr_football_integral.fumble_home
     *
     * @mbg.generated
     */
    public void setFumbleHome(Integer fumbleHome) {
        this.fumbleHome = fumbleHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.fumble_away
     *
     * @return the value of cr_football_integral.fumble_away
     *
     * @mbg.generated
     */
    public Integer getFumbleAway() {
        return fumbleAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.fumble_away
     *
     * @param fumbleAway the value for cr_football_integral.fumble_away
     *
     * @mbg.generated
     */
    public void setFumbleAway(Integer fumbleAway) {
        this.fumbleAway = fumbleAway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_integral.lei_data_integral_id
     *
     * @return the value of cr_football_integral.lei_data_integral_id
     *
     * @mbg.generated
     */
    public String getLeiDataIntegralId() {
        return leiDataIntegralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_integral.lei_data_integral_id
     *
     * @param leiDataIntegralId the value for cr_football_integral.lei_data_integral_id
     *
     * @mbg.generated
     */
    public void setLeiDataIntegralId(String leiDataIntegralId) {
        this.leiDataIntegralId = leiDataIntegralId == null ? null : leiDataIntegralId.trim();
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getFootballLeagueMatchName() {
        return footballLeagueMatchName;
    }

    public void setFootballLeagueMatchName(String footballLeagueMatchName) {
        this.footballLeagueMatchName = footballLeagueMatchName;
    }

    public String getFootballSeasonName() {
        return footballSeasonName;
    }

    public void setFootballSeasonName(String footballSeasonName) {
        this.footballSeasonName = footballSeasonName;
    }

    public String getFootballSeasonCategoryName() {
        return footballSeasonCategoryName;
    }

    public void setFootballSeasonCategoryName(String footballSeasonCategoryName) {
        this.footballSeasonCategoryName = footballSeasonCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballIntegral other = (FootballIntegral) that;
        return (this.getFootballIntegralId() == null ? other.getFootballIntegralId() == null : this.getFootballIntegralId().equals(other.getFootballIntegralId()))
            && (this.getFootballLeagueMatchId() == null ? other.getFootballLeagueMatchId() == null : this.getFootballLeagueMatchId().equals(other.getFootballLeagueMatchId()))
            && (this.getFootballSeasonId() == null ? other.getFootballSeasonId() == null : this.getFootballSeasonId().equals(other.getFootballSeasonId()))
            && (this.getFootballSeasonCategoryId() == null ? other.getFootballSeasonCategoryId() == null : this.getFootballSeasonCategoryId().equals(other.getFootballSeasonCategoryId()))
            && (this.getFootballTeamId() == null ? other.getFootballTeamId() == null : this.getFootballTeamId().equals(other.getFootballTeamId()))
            && (this.getIntegralTotal() == null ? other.getIntegralTotal() == null : this.getIntegralTotal().equals(other.getIntegralTotal()))
            && (this.getGoalTotal() == null ? other.getGoalTotal() == null : this.getGoalTotal().equals(other.getGoalTotal()))
            && (this.getFumbleTotal() == null ? other.getFumbleTotal() == null : this.getFumbleTotal().equals(other.getFumbleTotal()))
            && (this.getDifferenceTotal() == null ? other.getDifferenceTotal() == null : this.getDifferenceTotal().equals(other.getDifferenceTotal()))
            && (this.getPlayedTotal() == null ? other.getPlayedTotal() == null : this.getPlayedTotal().equals(other.getPlayedTotal()))
            && (this.getWinTotal() == null ? other.getWinTotal() == null : this.getWinTotal().equals(other.getWinTotal()))
            && (this.getDrawTotal() == null ? other.getDrawTotal() == null : this.getDrawTotal().equals(other.getDrawTotal()))
            && (this.getLostTotal() == null ? other.getLostTotal() == null : this.getLostTotal().equals(other.getLostTotal()))
            && (this.getGoalPerPlayed() == null ? other.getGoalPerPlayed() == null : this.getGoalPerPlayed().equals(other.getGoalPerPlayed()))
            && (this.getFumblePerPlayed() == null ? other.getFumblePerPlayed() == null : this.getFumblePerPlayed().equals(other.getFumblePerPlayed()))
            && (this.getWinPerPlayed() == null ? other.getWinPerPlayed() == null : this.getWinPerPlayed().equals(other.getWinPerPlayed()))
            && (this.getWinHome() == null ? other.getWinHome() == null : this.getWinHome().equals(other.getWinHome()))
            && (this.getWinAway() == null ? other.getWinAway() == null : this.getWinAway().equals(other.getWinAway()))
            && (this.getDrawHome() == null ? other.getDrawHome() == null : this.getDrawHome().equals(other.getDrawHome()))
            && (this.getDrawAway() == null ? other.getDrawAway() == null : this.getDrawAway().equals(other.getDrawAway()))
            && (this.getLostHome() == null ? other.getLostHome() == null : this.getLostHome().equals(other.getLostHome()))
            && (this.getLostAway() == null ? other.getLostAway() == null : this.getLostAway().equals(other.getLostAway()))
            && (this.getGoalHome() == null ? other.getGoalHome() == null : this.getGoalHome().equals(other.getGoalHome()))
            && (this.getGoalAway() == null ? other.getGoalAway() == null : this.getGoalAway().equals(other.getGoalAway()))
            && (this.getFumbleHome() == null ? other.getFumbleHome() == null : this.getFumbleHome().equals(other.getFumbleHome()))
            && (this.getFumbleAway() == null ? other.getFumbleAway() == null : this.getFumbleAway().equals(other.getFumbleAway()))
            && (this.getLeiDataIntegralId() == null ? other.getLeiDataIntegralId() == null : this.getLeiDataIntegralId().equals(other.getLeiDataIntegralId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballIntegralId() == null) ? 0 : getFootballIntegralId().hashCode());
        result = prime * result + ((getFootballLeagueMatchId() == null) ? 0 : getFootballLeagueMatchId().hashCode());
        result = prime * result + ((getFootballSeasonId() == null) ? 0 : getFootballSeasonId().hashCode());
        result = prime * result + ((getFootballSeasonCategoryId() == null) ? 0 : getFootballSeasonCategoryId().hashCode());
        result = prime * result + ((getFootballTeamId() == null) ? 0 : getFootballTeamId().hashCode());
        result = prime * result + ((getIntegralTotal() == null) ? 0 : getIntegralTotal().hashCode());
        result = prime * result + ((getGoalTotal() == null) ? 0 : getGoalTotal().hashCode());
        result = prime * result + ((getFumbleTotal() == null) ? 0 : getFumbleTotal().hashCode());
        result = prime * result + ((getDifferenceTotal() == null) ? 0 : getDifferenceTotal().hashCode());
        result = prime * result + ((getPlayedTotal() == null) ? 0 : getPlayedTotal().hashCode());
        result = prime * result + ((getWinTotal() == null) ? 0 : getWinTotal().hashCode());
        result = prime * result + ((getDrawTotal() == null) ? 0 : getDrawTotal().hashCode());
        result = prime * result + ((getLostTotal() == null) ? 0 : getLostTotal().hashCode());
        result = prime * result + ((getGoalPerPlayed() == null) ? 0 : getGoalPerPlayed().hashCode());
        result = prime * result + ((getFumblePerPlayed() == null) ? 0 : getFumblePerPlayed().hashCode());
        result = prime * result + ((getWinPerPlayed() == null) ? 0 : getWinPerPlayed().hashCode());
        result = prime * result + ((getWinHome() == null) ? 0 : getWinHome().hashCode());
        result = prime * result + ((getWinAway() == null) ? 0 : getWinAway().hashCode());
        result = prime * result + ((getDrawHome() == null) ? 0 : getDrawHome().hashCode());
        result = prime * result + ((getDrawAway() == null) ? 0 : getDrawAway().hashCode());
        result = prime * result + ((getLostHome() == null) ? 0 : getLostHome().hashCode());
        result = prime * result + ((getLostAway() == null) ? 0 : getLostAway().hashCode());
        result = prime * result + ((getGoalHome() == null) ? 0 : getGoalHome().hashCode());
        result = prime * result + ((getGoalAway() == null) ? 0 : getGoalAway().hashCode());
        result = prime * result + ((getFumbleHome() == null) ? 0 : getFumbleHome().hashCode());
        result = prime * result + ((getFumbleAway() == null) ? 0 : getFumbleAway().hashCode());
        result = prime * result + ((getLeiDataIntegralId() == null) ? 0 : getLeiDataIntegralId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballIntegralId=").append(footballIntegralId);
        sb.append(", footballLeagueMatchId=").append(footballLeagueMatchId);
        sb.append(", footballSeasonId=").append(footballSeasonId);
        sb.append(", footballSeasonCategoryId=").append(footballSeasonCategoryId);
        sb.append(", footballTeamId=").append(footballTeamId);
        sb.append(", integralTotal=").append(integralTotal);
        sb.append(", goalTotal=").append(goalTotal);
        sb.append(", fumbleTotal=").append(fumbleTotal);
        sb.append(", differenceTotal=").append(differenceTotal);
        sb.append(", playedTotal=").append(playedTotal);
        sb.append(", winTotal=").append(winTotal);
        sb.append(", drawTotal=").append(drawTotal);
        sb.append(", lostTotal=").append(lostTotal);
        sb.append(", goalPerPlayed=").append(goalPerPlayed);
        sb.append(", fumblePerPlayed=").append(fumblePerPlayed);
        sb.append(", winPerPlayed=").append(winPerPlayed);
        sb.append(", winHome=").append(winHome);
        sb.append(", winAway=").append(winAway);
        sb.append(", drawHome=").append(drawHome);
        sb.append(", drawAway=").append(drawAway);
        sb.append(", lostHome=").append(lostHome);
        sb.append(", lostAway=").append(lostAway);
        sb.append(", goalHome=").append(goalHome);
        sb.append(", goalAway=").append(goalAway);
        sb.append(", fumbleHome=").append(fumbleHome);
        sb.append(", fumbleAway=").append(fumbleAway);
        sb.append(", leiDataIntegralId=").append(leiDataIntegralId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}