package org.ys.crawler.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FootballScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public FootballScoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFootballScoreIdIsNull() {
            addCriterion("football_score_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdIsNotNull() {
            addCriterion("football_score_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdEqualTo(String value) {
            addCriterion("football_score_id =", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdNotEqualTo(String value) {
            addCriterion("football_score_id <>", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdGreaterThan(String value) {
            addCriterion("football_score_id >", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_score_id >=", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdLessThan(String value) {
            addCriterion("football_score_id <", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdLessThanOrEqualTo(String value) {
            addCriterion("football_score_id <=", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdLike(String value) {
            addCriterion("football_score_id like", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdNotLike(String value) {
            addCriterion("football_score_id not like", value, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdIn(List<String> values) {
            addCriterion("football_score_id in", values, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdNotIn(List<String> values) {
            addCriterion("football_score_id not in", values, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdBetween(String value1, String value2) {
            addCriterion("football_score_id between", value1, value2, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andFootballScoreIdNotBetween(String value1, String value2) {
            addCriterion("football_score_id not between", value1, value2, "footballScoreId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdIsNull() {
            addCriterion("home_football_team_id is null");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdIsNotNull() {
            addCriterion("home_football_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdEqualTo(String value) {
            addCriterion("home_football_team_id =", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdNotEqualTo(String value) {
            addCriterion("home_football_team_id <>", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdGreaterThan(String value) {
            addCriterion("home_football_team_id >", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("home_football_team_id >=", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdLessThan(String value) {
            addCriterion("home_football_team_id <", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdLessThanOrEqualTo(String value) {
            addCriterion("home_football_team_id <=", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdLike(String value) {
            addCriterion("home_football_team_id like", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdNotLike(String value) {
            addCriterion("home_football_team_id not like", value, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdIn(List<String> values) {
            addCriterion("home_football_team_id in", values, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdNotIn(List<String> values) {
            addCriterion("home_football_team_id not in", values, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdBetween(String value1, String value2) {
            addCriterion("home_football_team_id between", value1, value2, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeFootballTeamIdNotBetween(String value1, String value2) {
            addCriterion("home_football_team_id not between", value1, value2, "homeFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdIsNull() {
            addCriterion("away_football_team_id is null");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdIsNotNull() {
            addCriterion("away_football_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdEqualTo(String value) {
            addCriterion("away_football_team_id =", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdNotEqualTo(String value) {
            addCriterion("away_football_team_id <>", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdGreaterThan(String value) {
            addCriterion("away_football_team_id >", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("away_football_team_id >=", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdLessThan(String value) {
            addCriterion("away_football_team_id <", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdLessThanOrEqualTo(String value) {
            addCriterion("away_football_team_id <=", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdLike(String value) {
            addCriterion("away_football_team_id like", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdNotLike(String value) {
            addCriterion("away_football_team_id not like", value, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdIn(List<String> values) {
            addCriterion("away_football_team_id in", values, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdNotIn(List<String> values) {
            addCriterion("away_football_team_id not in", values, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdBetween(String value1, String value2) {
            addCriterion("away_football_team_id between", value1, value2, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andAwayFootballTeamIdNotBetween(String value1, String value2) {
            addCriterion("away_football_team_id not between", value1, value2, "awayFootballTeamId");
            return (Criteria) this;
        }

        public Criteria andHomeScoreIsNull() {
            addCriterion("home_score is null");
            return (Criteria) this;
        }

        public Criteria andHomeScoreIsNotNull() {
            addCriterion("home_score is not null");
            return (Criteria) this;
        }

        public Criteria andHomeScoreEqualTo(Integer value) {
            addCriterion("home_score =", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreNotEqualTo(Integer value) {
            addCriterion("home_score <>", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreGreaterThan(Integer value) {
            addCriterion("home_score >", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("home_score >=", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreLessThan(Integer value) {
            addCriterion("home_score <", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreLessThanOrEqualTo(Integer value) {
            addCriterion("home_score <=", value, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreIn(List<Integer> values) {
            addCriterion("home_score in", values, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreNotIn(List<Integer> values) {
            addCriterion("home_score not in", values, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreBetween(Integer value1, Integer value2) {
            addCriterion("home_score between", value1, value2, "homeScore");
            return (Criteria) this;
        }

        public Criteria andHomeScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("home_score not between", value1, value2, "homeScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreIsNull() {
            addCriterion("away_score is null");
            return (Criteria) this;
        }

        public Criteria andAwayScoreIsNotNull() {
            addCriterion("away_score is not null");
            return (Criteria) this;
        }

        public Criteria andAwayScoreEqualTo(Integer value) {
            addCriterion("away_score =", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreNotEqualTo(Integer value) {
            addCriterion("away_score <>", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreGreaterThan(Integer value) {
            addCriterion("away_score >", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("away_score >=", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreLessThan(Integer value) {
            addCriterion("away_score <", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreLessThanOrEqualTo(Integer value) {
            addCriterion("away_score <=", value, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreIn(List<Integer> values) {
            addCriterion("away_score in", values, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreNotIn(List<Integer> values) {
            addCriterion("away_score not in", values, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreBetween(Integer value1, Integer value2) {
            addCriterion("away_score between", value1, value2, "awayScore");
            return (Criteria) this;
        }

        public Criteria andAwayScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("away_score not between", value1, value2, "awayScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreIsNull() {
            addCriterion("half_home_score is null");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreIsNotNull() {
            addCriterion("half_home_score is not null");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreEqualTo(Integer value) {
            addCriterion("half_home_score =", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreNotEqualTo(Integer value) {
            addCriterion("half_home_score <>", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreGreaterThan(Integer value) {
            addCriterion("half_home_score >", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("half_home_score >=", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreLessThan(Integer value) {
            addCriterion("half_home_score <", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreLessThanOrEqualTo(Integer value) {
            addCriterion("half_home_score <=", value, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreIn(List<Integer> values) {
            addCriterion("half_home_score in", values, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreNotIn(List<Integer> values) {
            addCriterion("half_home_score not in", values, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreBetween(Integer value1, Integer value2) {
            addCriterion("half_home_score between", value1, value2, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfHomeScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("half_home_score not between", value1, value2, "halfHomeScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreIsNull() {
            addCriterion("half_away_score is null");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreIsNotNull() {
            addCriterion("half_away_score is not null");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreEqualTo(Integer value) {
            addCriterion("half_away_score =", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreNotEqualTo(Integer value) {
            addCriterion("half_away_score <>", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreGreaterThan(Integer value) {
            addCriterion("half_away_score >", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("half_away_score >=", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreLessThan(Integer value) {
            addCriterion("half_away_score <", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreLessThanOrEqualTo(Integer value) {
            addCriterion("half_away_score <=", value, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreIn(List<Integer> values) {
            addCriterion("half_away_score in", values, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreNotIn(List<Integer> values) {
            addCriterion("half_away_score not in", values, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreBetween(Integer value1, Integer value2) {
            addCriterion("half_away_score between", value1, value2, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andHalfAwayScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("half_away_score not between", value1, value2, "halfAwayScore");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNull() {
            addCriterion("match_date is null");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNotNull() {
            addCriterion("match_date is not null");
            return (Criteria) this;
        }

        public Criteria andMatchDateEqualTo(Date value) {
            addCriterionForJDBCDate("match_date =", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("match_date <>", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThan(Date value) {
            addCriterionForJDBCDate("match_date >", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("match_date >=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThan(Date value) {
            addCriterionForJDBCDate("match_date <", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("match_date <=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateIn(List<Date> values) {
            addCriterionForJDBCDate("match_date in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("match_date not in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("match_date between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("match_date not between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNull() {
            addCriterion("football_league_match_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIsNotNull() {
            addCriterion("football_league_match_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdEqualTo(String value) {
            addCriterion("football_league_match_id =", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotEqualTo(String value) {
            addCriterion("football_league_match_id <>", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThan(String value) {
            addCriterion("football_league_match_id >", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_league_match_id >=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThan(String value) {
            addCriterion("football_league_match_id <", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLessThanOrEqualTo(String value) {
            addCriterion("football_league_match_id <=", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdLike(String value) {
            addCriterion("football_league_match_id like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotLike(String value) {
            addCriterion("football_league_match_id not like", value, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdIn(List<String> values) {
            addCriterion("football_league_match_id in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotIn(List<String> values) {
            addCriterion("football_league_match_id not in", values, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdBetween(String value1, String value2) {
            addCriterion("football_league_match_id between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballLeagueMatchIdNotBetween(String value1, String value2) {
            addCriterion("football_league_match_id not between", value1, value2, "footballLeagueMatchId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIsNull() {
            addCriterion("football_season_category_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIsNotNull() {
            addCriterion("football_season_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdEqualTo(String value) {
            addCriterion("football_season_category_id =", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotEqualTo(String value) {
            addCriterion("football_season_category_id <>", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThan(String value) {
            addCriterion("football_season_category_id >", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_category_id >=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThan(String value) {
            addCriterion("football_season_category_id <", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_category_id <=", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdLike(String value) {
            addCriterion("football_season_category_id like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotLike(String value) {
            addCriterion("football_season_category_id not like", value, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdIn(List<String> values) {
            addCriterion("football_season_category_id in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotIn(List<String> values) {
            addCriterion("football_season_category_id not in", values, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdBetween(String value1, String value2) {
            addCriterion("football_season_category_id between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonCategoryIdNotBetween(String value1, String value2) {
            addCriterion("football_season_category_id not between", value1, value2, "footballSeasonCategoryId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNull() {
            addCriterion("football_season_id is null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIsNotNull() {
            addCriterion("football_season_id is not null");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdEqualTo(String value) {
            addCriterion("football_season_id =", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotEqualTo(String value) {
            addCriterion("football_season_id <>", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThan(String value) {
            addCriterion("football_season_id >", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdGreaterThanOrEqualTo(String value) {
            addCriterion("football_season_id >=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThan(String value) {
            addCriterion("football_season_id <", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLessThanOrEqualTo(String value) {
            addCriterion("football_season_id <=", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdLike(String value) {
            addCriterion("football_season_id like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotLike(String value) {
            addCriterion("football_season_id not like", value, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdIn(List<String> values) {
            addCriterion("football_season_id in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotIn(List<String> values) {
            addCriterion("football_season_id not in", values, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdBetween(String value1, String value2) {
            addCriterion("football_season_id between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andFootballSeasonIdNotBetween(String value1, String value2) {
            addCriterion("football_season_id not between", value1, value2, "footballSeasonId");
            return (Criteria) this;
        }

        public Criteria andRoundIsNull() {
            addCriterion("round is null");
            return (Criteria) this;
        }

        public Criteria andRoundIsNotNull() {
            addCriterion("round is not null");
            return (Criteria) this;
        }

        public Criteria andRoundEqualTo(String value) {
            addCriterion("round =", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotEqualTo(String value) {
            addCriterion("round <>", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThan(String value) {
            addCriterion("round >", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThanOrEqualTo(String value) {
            addCriterion("round >=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThan(String value) {
            addCriterion("round <", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThanOrEqualTo(String value) {
            addCriterion("round <=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLike(String value) {
            addCriterion("round like", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotLike(String value) {
            addCriterion("round not like", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundIn(List<String> values) {
            addCriterion("round in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotIn(List<String> values) {
            addCriterion("round not in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundBetween(String value1, String value2) {
            addCriterion("round between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotBetween(String value1, String value2) {
            addCriterion("round not between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdIsNull() {
            addCriterion("leidata_score_id is null");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdIsNotNull() {
            addCriterion("leidata_score_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdEqualTo(String value) {
            addCriterion("leidata_score_id =", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdNotEqualTo(String value) {
            addCriterion("leidata_score_id <>", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdGreaterThan(String value) {
            addCriterion("leidata_score_id >", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("leidata_score_id >=", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdLessThan(String value) {
            addCriterion("leidata_score_id <", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdLessThanOrEqualTo(String value) {
            addCriterion("leidata_score_id <=", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdLike(String value) {
            addCriterion("leidata_score_id like", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdNotLike(String value) {
            addCriterion("leidata_score_id not like", value, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdIn(List<String> values) {
            addCriterion("leidata_score_id in", values, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdNotIn(List<String> values) {
            addCriterion("leidata_score_id not in", values, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdBetween(String value1, String value2) {
            addCriterion("leidata_score_id between", value1, value2, "leidataScoreId");
            return (Criteria) this;
        }

        public Criteria andLeidataScoreIdNotBetween(String value1, String value2) {
            addCriterion("leidata_score_id not between", value1, value2, "leidataScoreId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_score
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}