package org.ys.crawler.model;

import java.io.Serializable;

public class FootballTeam implements Serializable {
    private static final long serialVersionUID = -833089533188397960L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_team.football_team_id
     *
     * @mbg.generated
     */
    private String footballTeamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_team.team_name
     *
     * @mbg.generated
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_team.team_other_name
     *
     * @mbg.generated
     */
    private String teamOtherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_team.team_comment
     *
     * @mbg.generated
     */
    private String teamComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cr_football_team.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_team.football_team_id
     *
     * @return the value of cr_football_team.football_team_id
     *
     * @mbg.generated
     */
    public String getFootballTeamId() {
        return footballTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_team.football_team_id
     *
     * @param footballTeamId the value for cr_football_team.football_team_id
     *
     * @mbg.generated
     */
    public void setFootballTeamId(String footballTeamId) {
        this.footballTeamId = footballTeamId == null ? null : footballTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_team.team_name
     *
     * @return the value of cr_football_team.team_name
     *
     * @mbg.generated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_team.team_name
     *
     * @param teamName the value for cr_football_team.team_name
     *
     * @mbg.generated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_team.team_other_name
     *
     * @return the value of cr_football_team.team_other_name
     *
     * @mbg.generated
     */
    public String getTeamOtherName() {
        return teamOtherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_team.team_other_name
     *
     * @param teamOtherName the value for cr_football_team.team_other_name
     *
     * @mbg.generated
     */
    public void setTeamOtherName(String teamOtherName) {
        this.teamOtherName = teamOtherName == null ? null : teamOtherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_team.team_comment
     *
     * @return the value of cr_football_team.team_comment
     *
     * @mbg.generated
     */
    public String getTeamComment() {
        return teamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_team.team_comment
     *
     * @param teamComment the value for cr_football_team.team_comment
     *
     * @mbg.generated
     */
    public void setTeamComment(String teamComment) {
        this.teamComment = teamComment == null ? null : teamComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cr_football_team.country
     *
     * @return the value of cr_football_team.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cr_football_team.country
     *
     * @param country the value for cr_football_team.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FootballTeam other = (FootballTeam) that;
        return (this.getFootballTeamId() == null ? other.getFootballTeamId() == null : this.getFootballTeamId().equals(other.getFootballTeamId()))
            && (this.getTeamName() == null ? other.getTeamName() == null : this.getTeamName().equals(other.getTeamName()))
            && (this.getTeamOtherName() == null ? other.getTeamOtherName() == null : this.getTeamOtherName().equals(other.getTeamOtherName()))
            && (this.getTeamComment() == null ? other.getTeamComment() == null : this.getTeamComment().equals(other.getTeamComment()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFootballTeamId() == null) ? 0 : getFootballTeamId().hashCode());
        result = prime * result + ((getTeamName() == null) ? 0 : getTeamName().hashCode());
        result = prime * result + ((getTeamOtherName() == null) ? 0 : getTeamOtherName().hashCode());
        result = prime * result + ((getTeamComment() == null) ? 0 : getTeamComment().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", footballTeamId=").append(footballTeamId);
        sb.append(", teamName=").append(teamName);
        sb.append(", teamOtherName=").append(teamOtherName);
        sb.append(", teamComment=").append(teamComment);
        sb.append(", country=").append(country);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}