package org.ys.crawler.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.ys.crawler.model.FootballSeasonCategory;
import org.ys.crawler.model.FootballSeasonCategoryExample;

@Repository
public interface FootballSeasonCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    long countByExample(FootballSeasonCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int deleteByExample(FootballSeasonCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String footballSeasonCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int insert(FootballSeasonCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int insertSelective(FootballSeasonCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    List<FootballSeasonCategory> selectByExample(FootballSeasonCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    FootballSeasonCategory selectByPrimaryKey(String footballSeasonCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FootballSeasonCategory record, @Param("example") FootballSeasonCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FootballSeasonCategory record, @Param("example") FootballSeasonCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootballSeasonCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_season_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootballSeasonCategory record);
}