package org.ys.crawler.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.ys.crawler.model.FootballTeam;
import org.ys.crawler.model.FootballTeamExample;

@Repository
public interface FootballTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    long countByExample(FootballTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int deleteByExample(FootballTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String footballTeamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int insert(FootballTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int insertSelective(FootballTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    List<FootballTeam> selectByExample(FootballTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    FootballTeam selectByPrimaryKey(String footballTeamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FootballTeam record, @Param("example") FootballTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FootballTeam record, @Param("example") FootballTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootballTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootballTeam record);
}