package org.ys.crawler.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.ys.crawler.model.FootballIntegral;
import org.ys.crawler.model.FootballIntegralExample;

import java.util.List;

@Repository
public interface FootballIntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    long countByExample(FootballIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int deleteByExample(FootballIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String footballIntegralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int insert(FootballIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int insertSelective(FootballIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    List<FootballIntegral> selectByExample(FootballIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    FootballIntegral selectByPrimaryKey(String footballIntegralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FootballIntegral record, @Param("example") FootballIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FootballIntegral record, @Param("example") FootballIntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootballIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_integral
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootballIntegral record);
}