package org.ys.crawler.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.ys.crawler.model.FootballScore;
import org.ys.crawler.model.FootballScoreExample;

@Repository
public interface FootballScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    long countByExample(FootballScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int deleteByExample(FootballScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String footballScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int insert(FootballScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int insertSelective(FootballScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    List<FootballScore> selectByExample(FootballScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    FootballScore selectByPrimaryKey(String footballScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FootballScore record, @Param("example") FootballScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FootballScore record, @Param("example") FootballScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootballScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootballScore record);
}