package org.ys.crawler.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.ys.crawler.model.FootballScoreDetail;
import org.ys.crawler.model.FootballScoreDetailExample;

@Repository
public interface FootballScoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    long countByExample(FootballScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int deleteByExample(FootballScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String footballScoreDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int insert(FootballScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int insertSelective(FootballScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    List<FootballScoreDetail> selectByExample(FootballScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    FootballScoreDetail selectByPrimaryKey(String footballScoreDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FootballScoreDetail record, @Param("example") FootballScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FootballScoreDetail record, @Param("example") FootballScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootballScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cr_football_score_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootballScoreDetail record);
}